In [1]:
print("Welcome to the Ai drug repurposing project!")

Welcome to the Ai drug repurposing project!

In [2]:
import pandas as pd 
import numpy as np
print("pandas version:",pd.__version__)
print("numpy version:",np.__version__)

pandas version: 3.0.3
numpy version: 2.5.1

In [3]:
import requests
print("requests version",requests.__version__)

requests version 2.34.2

In [4]:
import requests

url = "https://api.fda.gov/drug/label.json?limit=5"

response = requests.get(url)

print("Status Code:", response.status_code)

Status Code: 200

In [ ]:
import requests

url = "https://api.fda.gov/drug/label.json?limit=1"

response = requests.get(url)

data = response.json()

print(data)

In [ ]:
import requests

url = "https://api.fda.gov/drug/label.json?limit=1"

response = requests.get(url)

data = response.json()

print(data)

{'meta': {'disclaimer': 'Do not rely on openFDA to make decisions regarding medical care. While we make every effort to ensure that data is accurate, you should assume all results are unvalidated. We may limit or otherwise restrict your access to the API in line with our Terms of Service.', 'terms': 'https://open.fda.gov/terms/', 'license': 'https://open.fda.gov/license/', 'last_updated': '2026-08-01', 'results': {'skip': 0, 'limit': 1, 'total': 261258}}, 'results': [{'effective_time': '20210902', 'inactive_ingredient': ['INACTIVE INGREDIENTS Sucrose'], 'purpose': ['USES USES: Temporary Relief - Acne, Boils* * Claims based on traditional homeopathic practice, not accepted medical evidence. Not FDA evaluated.'], 'keep_out_of_reach_of_children': ['Keep this and all medication out of reach of children'], 'warnings': ['WARNINGS This product is to be used for self-limiting conditions If symptoms do not improve in 4 days, or worsen, discontinue use and seek assistance of health professional. As with any drug, if you are pregnant, or nursing a baby, seek professional advice before taking this product. Keep this and all medication out of reach of children Do not use if capseal is broken or missing. Close the cap tightly after use.'], 'questions': ['QUESTIONS OR COMMENTS www.Rxhomeo.com | 1.888.2796642 | info@rxhomeo.com Rxhomeo, Inc 3200 Commander Dr, Ste 100-W1, Carrollton, TX 75006 USA'], 'spl_product_data_elements': ['SILICEA SILICEA SUCROSE SILICON DIOXIDE SILICON DIOXIDE'], 'openfda': {'brand_name': ['SILICEA'], 'generic_name': ['SILICEA'], 'manufacturer_name': ['Rxhomeo Private Limited d.b.a. Rxhomeo, Inc'], 'product_ndc': ['15631-0404'], 'product_type': ['HUMAN OTC DRUG'], 'route': ['ORAL'], 'substance_name': ['SILICON DIOXIDE'], 'spl_id': ['ca7bbcc8-2354-375c-e053-2995a90a72a0'], 'spl_set_id': ['0000025c-6dbf-4af7-a741-5cbacaed519a'], 'package_ndc': ['15631-0404-0', '15631-0404-1', '15631-0404-2', '15631-0404-3', '15631-0404-4', '15631-0404-5', '15631-0404-6', '15631-0404-7'], 'is_original_packager': [True], 'upc': ['8907460005526'], 'unii': ['ETJ7Z6XBU4']}, 'version': '2', 'dosage_and_administration': ['DOSAGE Adults- Take 4 or 6 Pellets by mouth, three times daily or as suggested by physician. Children 2 years and older- take 1/2 the adult dose.'], 'pregnancy_or_breast_feeding': ['As with any drug, if you are pregnant, or nursing a baby, seek professional advice before taking this product.'], 'stop_use': ['If symptoms do not improve in 4 days, or worsen, discontinue use and seek assistance of health professional.'], 'storage_and_handling': ['STORAGE Store in a cool dark place'], 'do_not_use': ['Do not use if capseal is broken or missing. Close the cap tightly after use.'], 'package_label_principal_display_panel': ['Mini-Label Label-Pellets Blister-Pack Carton-Pack'], 'indications_and_usage': ['INDICATIONS Condition listed above or as directed by the physician'], 'set_id': '0000025c-6dbf-4af7-a741-5cbacaed519a', 'id': 'ca7bbcc8-2354-375c-e053-2995a90a72a0', 'active_ingredient': ['ACTIVE INGREDIENT SILICEA HPUS 2X and higher']}]}

In [2]:
print(data.keys())

dict_keys(['meta', 'results'])

In [3]:
print(type(data)['results'])

dict['results']

In [4]:
print(type(data["results"][0]))

<class 'dict'>

In [6]:
print(type(data))

<class 'dict'>

In [8]:
print(type(data["results"]))

<class 'list'>

In [9]:
print(type(data["results"][0]))

<class 'dict'>

In [10]:
drug=data["results"][0]

In [11]:
print(drug.keys())

dict_keys(['effective_time', 'inactive_ingredient', 'purpose', 'keep_out_of_reach_of_children', 'warnings', 'questions', 'spl_product_data_elements', 'openfda', 'version', 'dosage_and_administration', 'pregnancy_or_breast_feeding', 'stop_use', 'storage_and_handling', 'do_not_use', 'package_label_principal_display_panel', 'indications_and_usage', 'set_id', 'id', 'active_ingredient'])

In [12]:
print(drug["purpose"])

['USES USES: Temporary Relief - Acne, Boils* * Claims based on traditional homeopathic practice, not accepted medical evidence. Not FDA evaluated.']

In [2]:
print(drug["purpose"][0])

NameError: name 'drug' is not defined

In [3]:
drug = data["results"][0]

NameError: name 'data' is not defined

In [4]:
drug = data["results"][0]

NameError: name 'data' is not defined

In [5]:
import requests

In [6]:
url = "https://api.fda.gov/drug/label.json?limit=1"

In [7]:
response = requests.get(url)

In [8]:
data = response.json()

In [9]:
drug = data["results"][0]

In [10]:
print(drug["purpose"])

['USES USES: Temporary Relief - Acne, Boils* * Claims based on traditional homeopathic practice, not accepted medical evidence. Not FDA evaluated.']

In [11]:
print(drug["purpose"][0])

USES USES: Temporary Relief - Acne, Boils* * Claims based on traditional homeopathic practice, not accepted medical evidence. Not FDA evaluated.

In [12]:
print(drug["purpose"])

['USES USES: Temporary Relief - Acne, Boils* * Claims based on traditional homeopathic practice, not accepted medical evidence. Not FDA evaluated.']

In [13]:
print(drug["purpose"][0])

USES USES: Temporary Relief - Acne, Boils* * Claims based on traditional homeopathic practice, not accepted medical evidence. Not FDA evaluated.

In [14]:
print(type(drug["purpose"]))

<class 'list'>

In [15]:
print("openfda" in drug)

True

In [16]:
print(drug["openfda"].keys())

dict_keys(['brand_name', 'generic_name', 'manufacturer_name', 'product_ndc', 'product_type', 'route', 'substance_name', 'spl_id', 'spl_set_id', 'package_ndc', 'is_original_packager', 'upc', 'unii'])

In [17]:
print(drug["openfda"]["brand_name"])

['SILICEA']

In [18]:
print(drug["openfda"]["generic_name"])

['SILICEA']

In [19]:
print(drug["openfda"]["manufacturer_name"])

['Rxhomeo Private Limited d.b.a. Rxhomeo, Inc']

In [20]:
brand = drug["openfda"]["brand_name"][0]

In [21]:
generic = drug["openfda"]["generic_name"][0]

In [22]:
manufacturer = drug["openfda"]["manufacturer_name"][0]

In [23]:
print(brand)
print(generic)
print(manufacturer)

SILICEA
SILICEA
Rxhomeo Private Limited d.b.a. Rxhomeo, Inc

In [1]:
import requests

url = "https://api.fda.gov/drug/label.json?limit=50"

response = requests.get(url)
data = response.json()

print(len(data["results"]))

50

In [2]:
for drug in data["results"]:
    print(drug.keys())

dict_keys(['effective_time', 'inactive_ingredient', 'purpose', 'keep_out_of_reach_of_children', 'warnings', 'questions', 'spl_product_data_elements', 'openfda', 'version', 'dosage_and_administration', 'pregnancy_or_breast_feeding', 'stop_use', 'storage_and_handling', 'do_not_use', 'package_label_principal_display_panel', 'indications_and_usage', 'set_id', 'id', 'active_ingredient'])
dict_keys(['effective_time', 'inactive_ingredient', 'purpose', 'keep_out_of_reach_of_children', 'warnings', 'when_using', 'spl_product_data_elements', 'openfda', 'version', 'dosage_and_administration', 'package_label_principal_display_panel', 'indications_and_usage', 'set_id', 'id', 'active_ingredient'])
dict_keys(['spl_product_data_elements', 'active_ingredient', 'purpose', 'indications_and_usage', 'warnings', 'do_not_use', 'ask_doctor', 'stop_use', 'keep_out_of_reach_of_children', 'dosage_and_administration', 'storage_and_handling', 'inactive_ingredient', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['spl_product_data_elements', 'active_ingredient', 'purpose', 'keep_out_of_reach_of_children', 'indications_and_usage', 'warnings', 'dosage_and_administration', 'inactive_ingredient', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['spl_product_data_elements', 'spl_unclassified_section', 'description', 'clinical_pharmacology', 'clinical_pharmacology_table', 'pharmacokinetics', 'microbiology', 'microbiology_table', 'clinical_studies', 'indications_and_usage', 'spl_unclassified_section_table', 'contraindications', 'warnings', 'precautions', 'general_precautions', 'information_for_patients', 'drug_interactions', 'carcinogenesis_and_mutagenesis_and_impairment_of_fertility', 'pregnancy', 'nonteratogenic_effects', 'nursing_mothers', 'pediatric_use', 'geriatric_use', 'adverse_reactions', 'dosage_and_administration', 'dosage_and_administration_table', 'how_supplied', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['spl_product_data_elements', 'recent_major_changes', 'boxed_warning', 'indications_and_usage', 'dosage_and_administration', 'dosage_and_administration_table', 'dosage_forms_and_strengths', 'contraindications', 'warnings_and_cautions', 'adverse_reactions', 'drug_interactions', 'drug_interactions_table', 'use_in_specific_populations', 'pregnancy', 'pediatric_use', 'geriatric_use', 'overdosage', 'description', 'clinical_pharmacology', 'mechanism_of_action', 'pharmacodynamics', 'pharmacokinetics', 'nonclinical_toxicology', 'carcinogenesis_and_mutagenesis_and_impairment_of_fertility', 'clinical_studies', 'how_supplied', 'information_for_patients', 'spl_medguide', 'spl_medguide_table', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['effective_time', 'inactive_ingredient', 'purpose', 'keep_out_of_reach_of_children', 'warnings', 'when_using', 'questions', 'spl_product_data_elements', 'openfda', 'version', 'dosage_and_administration', 'spl_unclassified_section', 'stop_use', 'storage_and_handling', 'do_not_use', 'package_label_principal_display_panel', 'indications_and_usage', 'set_id', 'id', 'active_ingredient'])
dict_keys(['spl_product_data_elements', 'active_ingredient', 'purpose', 'indications_and_usage', 'warnings', 'when_using', 'stop_use', 'keep_out_of_reach_of_children', 'dosage_and_administration', 'inactive_ingredient', 'questions', 'spl_unclassified_section', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['effective_time', 'inactive_ingredient', 'purpose', 'keep_out_of_reach_of_children', 'warnings', 'spl_product_data_elements', 'openfda', 'version', 'dosage_and_administration', 'package_label_principal_display_panel', 'indications_and_usage', 'set_id', 'id', 'active_ingredient'])
dict_keys(['effective_time', 'inactive_ingredient', 'purpose', 'keep_out_of_reach_of_children', 'warnings', 'spl_product_data_elements', 'openfda', 'version', 'dosage_and_administration', 'pregnancy_or_breast_feeding', 'package_label_principal_display_panel', 'indications_and_usage', 'set_id', 'id', 'active_ingredient'])
dict_keys(['spl_product_data_elements', 'spl_unclassified_section', 'active_ingredient', 'purpose', 'indications_and_usage', 'warnings', 'when_using', 'keep_out_of_reach_of_children', 'dosage_and_administration', 'inactive_ingredient', 'questions', 'adverse_reactions', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['spl_product_data_elements', 'indications_and_usage', 'dosage_and_administration', 'active_ingredient', 'inactive_ingredient', 'purpose', 'keep_out_of_reach_of_children', 'warnings', 'questions', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['spl_product_data_elements', 'recent_major_changes', 'recent_major_changes_table', 'indications_and_usage', 'dosage_and_administration', 'dosage_and_administration_table', 'dosage_forms_and_strengths', 'contraindications', 'warnings_and_cautions', 'adverse_reactions', 'adverse_reactions_table', 'drug_interactions', 'use_in_specific_populations', 'pregnancy', 'pediatric_use', 'geriatric_use', 'overdosage', 'description', 'clinical_pharmacology', 'mechanism_of_action', 'pharmacodynamics', 'pharmacokinetics', 'nonclinical_toxicology', 'carcinogenesis_and_mutagenesis_and_impairment_of_fertility', 'clinical_studies', 'clinical_studies_table', 'how_supplied', 'information_for_patients', 'spl_patient_package_insert', 'spl_patient_package_insert_table', 'instructions_for_use', 'instructions_for_use_table', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['effective_time', 'drug_interactions', 'geriatric_use', 'precautions', 'description', 'clinical_pharmacology_table', 'mechanism_of_action', 'indications_and_usage', 'set_id', 'id', 'dosage_and_administration_table', 'pediatric_use', 'contraindications', 'drug_abuse_and_dependence', 'warnings', 'pregnancy', 'nursing_mothers', 'spl_product_data_elements', 'adverse_reactions_table', 'drug_and_or_laboratory_test_interactions', 'openfda', 'version', 'dosage_and_administration', 'adverse_reactions', 'how_supplied_table', 'laboratory_tests', 'how_supplied', 'information_for_patients', 'clinical_studies', 'package_label_principal_display_panel', 'clinical_pharmacology', 'carcinogenesis_and_mutagenesis_and_impairment_of_fertility', 'overdosage', 'warnings_table'])
dict_keys(['spl_product_data_elements', 'indications_and_usage', 'dosage_and_administration', 'dosage_forms_and_strengths', 'contraindications', 'warnings_and_cautions', 'adverse_reactions', 'adverse_reactions_table', 'drug_interactions', 'use_in_specific_populations', 'use_in_specific_populations_table', 'pregnancy', 'pediatric_use', 'pediatric_use_table', 'geriatric_use', 'overdosage', 'description', 'clinical_pharmacology', 'mechanism_of_action', 'pharmacodynamics', 'pharmacokinetics', 'nonclinical_toxicology', 'carcinogenesis_and_mutagenesis_and_impairment_of_fertility', 'clinical_studies', 'clinical_studies_table', 'how_supplied', 'information_for_patients', 'spl_unclassified_section', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['effective_time', 'drug_interactions', 'geriatric_use', 'references', 'precautions', 'description', 'clinical_pharmacology_table', 'general_precautions', 'storage_and_handling', 'clinical_studies_table', 'indications_and_usage', 'set_id', 'id', 'teratogenic_effects', 'dosage_and_administration_table', 'pediatric_use', 'contraindications', 'warnings', 'pregnancy', 'nursing_mothers', 'spl_product_data_elements', 'boxed_warning', 'openfda', 'version', 'dosage_and_administration', 'adverse_reactions', 'animal_pharmacology_and_or_toxicology', 'spl_unclassified_section', 'how_supplied', 'information_for_patients', 'clinical_studies', 'package_label_principal_display_panel', 'clinical_pharmacology', 'carcinogenesis_and_mutagenesis_and_impairment_of_fertility', 'overdosage'])
dict_keys(['spl_product_data_elements', 'spl_unclassified_section', 'description', 'clinical_pharmacology', 'pharmacokinetics', 'indications_and_usage', 'contraindications', 'warnings', 'precautions', 'information_for_patients', 'drug_interactions', 'drug_and_or_laboratory_test_interactions', 'carcinogenesis_and_mutagenesis_and_impairment_of_fertility', 'pregnancy', 'teratogenic_effects', 'nursing_mothers', 'pediatric_use', 'adverse_reactions', 'overdosage', 'dosage_and_administration', 'how_supplied', 'storage_and_handling', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['spl_product_data_elements', 'active_ingredient', 'purpose', 'indications_and_usage', 'warnings', 'do_not_use', 'when_using', 'stop_use', 'keep_out_of_reach_of_children', 'dosage_and_administration', 'storage_and_handling', 'inactive_ingredient', 'questions', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['spl_product_data_elements', 'description', 'clinical_pharmacology', 'pharmacokinetics', 'indications_and_usage', 'contraindications', 'warnings', 'boxed_warning', 'precautions', 'information_for_patients', 'laboratory_tests', 'drug_interactions', 'drug_and_or_laboratory_test_interactions', 'carcinogenesis_and_mutagenesis_and_impairment_of_fertility', 'pregnancy', 'nursing_mothers', 'pediatric_use', 'adverse_reactions', 'overdosage', 'dosage_and_administration', 'dosage_and_administration_table', 'how_supplied', 'storage_and_handling', 'spl_unclassified_section', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['spl_product_data_elements', 'indications_and_usage', 'dosage_and_administration', 'dosage_and_administration_table', 'dosage_forms_and_strengths', 'contraindications', 'warnings_and_cautions', 'adverse_reactions', 'adverse_reactions_table', 'drug_interactions', 'use_in_specific_populations', 'use_in_specific_populations_table', 'pregnancy', 'pregnancy_table', 'labor_and_delivery', 'pediatric_use', 'geriatric_use', 'drug_abuse_and_dependence', 'controlled_substance', 'dependence', 'overdosage', 'description', 'clinical_pharmacology', 'mechanism_of_action', 'pharmacokinetics', 'nonclinical_toxicology', 'carcinogenesis_and_mutagenesis_and_impairment_of_fertility', 'clinical_studies', 'clinical_studies_table', 'how_supplied', 'information_for_patients', 'spl_medguide', 'spl_medguide_table', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['spl_product_data_elements', 'warnings_and_cautions', 'active_ingredient', 'purpose', 'indications_and_usage', 'warnings', 'do_not_use', 'when_using', 'ask_doctor', 'keep_out_of_reach_of_children', 'dosage_and_administration', 'storage_and_handling', 'inactive_ingredient', 'questions', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['effective_time', 'purpose', 'keep_out_of_reach_of_children', 'when_using', 'questions', 'pregnancy_or_breast_feeding', 'storage_and_handling', 'indications_and_usage', 'set_id', 'id', 'ask_doctor_or_pharmacist', 'active_ingredient', 'dosage_and_administration_table', 'inactive_ingredient', 'warnings', 'spl_product_data_elements', 'ask_doctor', 'openfda', 'version', 'dosage_and_administration', 'stop_use', 'do_not_use', 'package_label_principal_display_panel'])
dict_keys(['spl_product_data_elements', 'spl_unclassified_section', 'active_ingredient', 'active_ingredient_table', 'purpose', 'purpose_table', 'indications_and_usage', 'warnings', 'when_using', 'stop_use', 'pregnancy_or_breast_feeding', 'keep_out_of_reach_of_children', 'dosage_and_administration', 'storage_and_handling', 'inactive_ingredient', 'questions', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['spl_product_data_elements', 'active_ingredient', 'purpose', 'indications_and_usage', 'warnings', 'do_not_use', 'ask_doctor', 'ask_doctor_or_pharmacist', 'stop_use', 'pregnancy_or_breast_feeding', 'keep_out_of_reach_of_children', 'dosage_and_administration', 'storage_and_handling', 'inactive_ingredient', 'questions', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['effective_time', 'inactive_ingredient', 'purpose', 'keep_out_of_reach_of_children', 'when_using', 'spl_product_data_elements', 'openfda', 'version', 'dosage_and_administration', 'package_label_principal_display_panel', 'indications_and_usage', 'set_id', 'id', 'active_ingredient'])
dict_keys(['effective_time', 'inactive_ingredient', 'purpose', 'keep_out_of_reach_of_children', 'warnings', 'when_using', 'questions', 'spl_product_data_elements', 'openfda', 'version', 'dosage_and_administration', 'stop_use', 'storage_and_handling', 'do_not_use', 'package_label_principal_display_panel', 'indications_and_usage', 'set_id', 'id', 'active_ingredient'])
dict_keys(['effective_time', 'recent_major_changes', 'drug_interactions', 'geriatric_use', 'pharmacodynamics', 'description', 'nonclinical_toxicology', 'dosage_forms_and_strengths', 'clinical_pharmacology_table', 'storage_and_handling', 'mechanism_of_action', 'pharmacokinetics', 'clinical_studies_table', 'indications_and_usage', 'set_id', 'id', 'pediatric_use', 'contraindications', 'pregnancy', 'nursing_mothers', 'spl_product_data_elements', 'boxed_warning', 'warnings_and_cautions', 'adverse_reactions_table', 'openfda', 'recent_major_changes_table', 'version', 'dosage_and_administration', 'adverse_reactions', 'spl_unclassified_section', 'use_in_specific_populations', 'how_supplied', 'information_for_patients', 'clinical_studies', 'package_label_principal_display_panel', 'clinical_pharmacology', 'carcinogenesis_and_mutagenesis_and_impairment_of_fertility', 'overdosage'])
dict_keys(['spl_product_data_elements', 'active_ingredient', 'purpose', 'indications_and_usage', 'warnings', 'do_not_use', 'ask_doctor', 'ask_doctor_or_pharmacist', 'when_using', 'stop_use', 'pregnancy_or_breast_feeding', 'keep_out_of_reach_of_children', 'dosage_and_administration', 'storage_and_handling', 'inactive_ingredient', 'questions', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['spl_product_data_elements', 'spl_unclassified_section', 'active_ingredient', 'purpose', 'indications_and_usage', 'warnings', 'do_not_use', 'when_using', 'stop_use', 'keep_out_of_reach_of_children', 'dosage_and_administration', 'questions', 'storage_and_handling', 'inactive_ingredient', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['effective_time', 'drug_interactions', 'precautions', 'description', 'clinical_pharmacology_table', 'general_precautions', 'indications_and_usage', 'set_id', 'id', 'pediatric_use', 'contraindications', 'warnings', 'pregnancy', 'nursing_mothers', 'spl_product_data_elements', 'openfda', 'version', 'dosage_and_administration', 'adverse_reactions', 'spl_unclassified_section', 'laboratory_tests', 'how_supplied', 'package_label_principal_display_panel', 'clinical_pharmacology', 'carcinogenesis_and_mutagenesis_and_impairment_of_fertility', 'overdosage'])
dict_keys(['spl_product_data_elements', 'spl_unclassified_section', 'description', 'clinical_pharmacology', 'indications_and_usage', 'contraindications', 'warnings', 'precautions', 'general_precautions', 'information_for_patients', 'carcinogenesis_and_mutagenesis_and_impairment_of_fertility', 'pregnancy', 'teratogenic_effects', 'nonteratogenic_effects', 'nursing_mothers', 'pediatric_use', 'geriatric_use', 'adverse_reactions', 'dosage_and_administration', 'how_supplied', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['effective_time', 'contraindications', 'drug_abuse_and_dependence', 'precautions', 'warnings', 'spl_product_data_elements', 'description', 'openfda', 'version', 'dosage_and_administration', 'adverse_reactions', 'how_supplied_table', 'how_supplied', 'package_label_principal_display_panel', 'indications_and_usage', 'clinical_pharmacology', 'set_id', 'id', 'overdosage'])
dict_keys(['spl_product_data_elements', 'spl_unclassified_section', 'active_ingredient', 'purpose', 'indications_and_usage', 'warnings', 'when_using', 'stop_use', 'keep_out_of_reach_of_children', 'dosage_and_administration', 'inactive_ingredient', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['spl_product_data_elements', 'indications_and_usage', 'dosage_and_administration', 'active_ingredient', 'purpose', 'inactive_ingredient', 'questions', 'warnings', 'pregnancy_or_breast_feeding', 'keep_out_of_reach_of_children', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['effective_time', 'contraindications', 'precautions', 'warnings', 'spl_product_data_elements', 'description', 'adverse_reactions_table', 'openfda', 'version', 'dosage_and_administration', 'adverse_reactions', 'spl_unclassified_section', 'storage_and_handling', 'how_supplied', 'package_label_principal_display_panel', 'indications_and_usage', 'clinical_pharmacology', 'set_id', 'id', 'overdosage'])
dict_keys(['effective_time', 'keep_out_of_reach_of_children', 'warnings', 'spl_product_data_elements', 'openfda', 'version', 'dosage_and_administration', 'spl_unclassified_section', 'storage_and_handling', 'do_not_use', 'package_label_principal_display_panel', 'indications_and_usage', 'set_id', 'id', 'active_ingredient'])
dict_keys(['effective_time', 'references', 'precautions', 'description', 'clinical_pharmacology_table', 'indications_and_usage', 'set_id', 'id', 'dosage_and_administration_table', 'contraindications', 'warnings', 'spl_product_data_elements', 'boxed_warning', 'openfda', 'version', 'dosage_and_administration', 'adverse_reactions', 'animal_pharmacology_and_or_toxicology', 'spl_unclassified_section', 'how_supplied_table', 'how_supplied', 'references_table', 'package_label_principal_display_panel', 'clinical_pharmacology', 'overdosage'])
dict_keys(['effective_time', 'inactive_ingredient', 'purpose', 'keep_out_of_reach_of_children', 'warnings', 'when_using', 'spl_product_data_elements', 'openfda', 'version', 'dosage_and_administration', 'spl_unclassified_section', 'stop_use', 'package_label_principal_display_panel', 'indications_and_usage', 'set_id', 'id', 'active_ingredient'])
dict_keys(['spl_product_data_elements', 'indications_and_usage', 'dosage_and_administration', 'dosage_forms_and_strengths', 'contraindications', 'warnings_and_cautions', 'adverse_reactions', 'adverse_reactions_table', 'drug_interactions', 'use_in_specific_populations', 'pregnancy', 'pediatric_use', 'geriatric_use', 'overdosage', 'description', 'clinical_pharmacology', 'clinical_pharmacology_table', 'mechanism_of_action', 'pharmacodynamics', 'pharmacokinetics', 'pharmacokinetics_table', 'nonclinical_toxicology', 'carcinogenesis_and_mutagenesis_and_impairment_of_fertility', 'clinical_studies', 'clinical_studies_table', 'how_supplied', 'information_for_patients', 'spl_patient_package_insert', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['effective_time', 'inactive_ingredient', 'purpose', 'keep_out_of_reach_of_children', 'warnings', 'questions', 'spl_product_data_elements', 'openfda', 'version', 'dosage_and_administration', 'package_label_principal_display_panel', 'indications_and_usage', 'set_id', 'id', 'active_ingredient'])

In [3]:
for drug in data["results"]:

_IncompleteInputError: incomplete input (2250279295.py, line 1)

In [4]:
for drug in data["results"]:
    print(drug.keys())

dict_keys(['effective_time', 'inactive_ingredient', 'purpose', 'keep_out_of_reach_of_children', 'warnings', 'questions', 'spl_product_data_elements', 'openfda', 'version', 'dosage_and_administration', 'pregnancy_or_breast_feeding', 'stop_use', 'storage_and_handling', 'do_not_use', 'package_label_principal_display_panel', 'indications_and_usage', 'set_id', 'id', 'active_ingredient'])
dict_keys(['effective_time', 'inactive_ingredient', 'purpose', 'keep_out_of_reach_of_children', 'warnings', 'when_using', 'spl_product_data_elements', 'openfda', 'version', 'dosage_and_administration', 'package_label_principal_display_panel', 'indications_and_usage', 'set_id', 'id', 'active_ingredient'])
dict_keys(['spl_product_data_elements', 'active_ingredient', 'purpose', 'indications_and_usage', 'warnings', 'do_not_use', 'ask_doctor', 'stop_use', 'keep_out_of_reach_of_children', 'dosage_and_administration', 'storage_and_handling', 'inactive_ingredient', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['spl_product_data_elements', 'active_ingredient', 'purpose', 'keep_out_of_reach_of_children', 'indications_and_usage', 'warnings', 'dosage_and_administration', 'inactive_ingredient', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['spl_product_data_elements', 'spl_unclassified_section', 'description', 'clinical_pharmacology', 'clinical_pharmacology_table', 'pharmacokinetics', 'microbiology', 'microbiology_table', 'clinical_studies', 'indications_and_usage', 'spl_unclassified_section_table', 'contraindications', 'warnings', 'precautions', 'general_precautions', 'information_for_patients', 'drug_interactions', 'carcinogenesis_and_mutagenesis_and_impairment_of_fertility', 'pregnancy', 'nonteratogenic_effects', 'nursing_mothers', 'pediatric_use', 'geriatric_use', 'adverse_reactions', 'dosage_and_administration', 'dosage_and_administration_table', 'how_supplied', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['spl_product_data_elements', 'recent_major_changes', 'boxed_warning', 'indications_and_usage', 'dosage_and_administration', 'dosage_and_administration_table', 'dosage_forms_and_strengths', 'contraindications', 'warnings_and_cautions', 'adverse_reactions', 'drug_interactions', 'drug_interactions_table', 'use_in_specific_populations', 'pregnancy', 'pediatric_use', 'geriatric_use', 'overdosage', 'description', 'clinical_pharmacology', 'mechanism_of_action', 'pharmacodynamics', 'pharmacokinetics', 'nonclinical_toxicology', 'carcinogenesis_and_mutagenesis_and_impairment_of_fertility', 'clinical_studies', 'how_supplied', 'information_for_patients', 'spl_medguide', 'spl_medguide_table', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['effective_time', 'inactive_ingredient', 'purpose', 'keep_out_of_reach_of_children', 'warnings', 'when_using', 'questions', 'spl_product_data_elements', 'openfda', 'version', 'dosage_and_administration', 'spl_unclassified_section', 'stop_use', 'storage_and_handling', 'do_not_use', 'package_label_principal_display_panel', 'indications_and_usage', 'set_id', 'id', 'active_ingredient'])
dict_keys(['spl_product_data_elements', 'active_ingredient', 'purpose', 'indications_and_usage', 'warnings', 'when_using', 'stop_use', 'keep_out_of_reach_of_children', 'dosage_and_administration', 'inactive_ingredient', 'questions', 'spl_unclassified_section', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['effective_time', 'inactive_ingredient', 'purpose', 'keep_out_of_reach_of_children', 'warnings', 'spl_product_data_elements', 'openfda', 'version', 'dosage_and_administration', 'package_label_principal_display_panel', 'indications_and_usage', 'set_id', 'id', 'active_ingredient'])
dict_keys(['effective_time', 'inactive_ingredient', 'purpose', 'keep_out_of_reach_of_children', 'warnings', 'spl_product_data_elements', 'openfda', 'version', 'dosage_and_administration', 'pregnancy_or_breast_feeding', 'package_label_principal_display_panel', 'indications_and_usage', 'set_id', 'id', 'active_ingredient'])
dict_keys(['spl_product_data_elements', 'spl_unclassified_section', 'active_ingredient', 'purpose', 'indications_and_usage', 'warnings', 'when_using', 'keep_out_of_reach_of_children', 'dosage_and_administration', 'inactive_ingredient', 'questions', 'adverse_reactions', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['spl_product_data_elements', 'indications_and_usage', 'dosage_and_administration', 'active_ingredient', 'inactive_ingredient', 'purpose', 'keep_out_of_reach_of_children', 'warnings', 'questions', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['spl_product_data_elements', 'recent_major_changes', 'recent_major_changes_table', 'indications_and_usage', 'dosage_and_administration', 'dosage_and_administration_table', 'dosage_forms_and_strengths', 'contraindications', 'warnings_and_cautions', 'adverse_reactions', 'adverse_reactions_table', 'drug_interactions', 'use_in_specific_populations', 'pregnancy', 'pediatric_use', 'geriatric_use', 'overdosage', 'description', 'clinical_pharmacology', 'mechanism_of_action', 'pharmacodynamics', 'pharmacokinetics', 'nonclinical_toxicology', 'carcinogenesis_and_mutagenesis_and_impairment_of_fertility', 'clinical_studies', 'clinical_studies_table', 'how_supplied', 'information_for_patients', 'spl_patient_package_insert', 'spl_patient_package_insert_table', 'instructions_for_use', 'instructions_for_use_table', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['effective_time', 'drug_interactions', 'geriatric_use', 'precautions', 'description', 'clinical_pharmacology_table', 'mechanism_of_action', 'indications_and_usage', 'set_id', 'id', 'dosage_and_administration_table', 'pediatric_use', 'contraindications', 'drug_abuse_and_dependence', 'warnings', 'pregnancy', 'nursing_mothers', 'spl_product_data_elements', 'adverse_reactions_table', 'drug_and_or_laboratory_test_interactions', 'openfda', 'version', 'dosage_and_administration', 'adverse_reactions', 'how_supplied_table', 'laboratory_tests', 'how_supplied', 'information_for_patients', 'clinical_studies', 'package_label_principal_display_panel', 'clinical_pharmacology', 'carcinogenesis_and_mutagenesis_and_impairment_of_fertility', 'overdosage', 'warnings_table'])
dict_keys(['spl_product_data_elements', 'indications_and_usage', 'dosage_and_administration', 'dosage_forms_and_strengths', 'contraindications', 'warnings_and_cautions', 'adverse_reactions', 'adverse_reactions_table', 'drug_interactions', 'use_in_specific_populations', 'use_in_specific_populations_table', 'pregnancy', 'pediatric_use', 'pediatric_use_table', 'geriatric_use', 'overdosage', 'description', 'clinical_pharmacology', 'mechanism_of_action', 'pharmacodynamics', 'pharmacokinetics', 'nonclinical_toxicology', 'carcinogenesis_and_mutagenesis_and_impairment_of_fertility', 'clinical_studies', 'clinical_studies_table', 'how_supplied', 'information_for_patients', 'spl_unclassified_section', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['effective_time', 'drug_interactions', 'geriatric_use', 'references', 'precautions', 'description', 'clinical_pharmacology_table', 'general_precautions', 'storage_and_handling', 'clinical_studies_table', 'indications_and_usage', 'set_id', 'id', 'teratogenic_effects', 'dosage_and_administration_table', 'pediatric_use', 'contraindications', 'warnings', 'pregnancy', 'nursing_mothers', 'spl_product_data_elements', 'boxed_warning', 'openfda', 'version', 'dosage_and_administration', 'adverse_reactions', 'animal_pharmacology_and_or_toxicology', 'spl_unclassified_section', 'how_supplied', 'information_for_patients', 'clinical_studies', 'package_label_principal_display_panel', 'clinical_pharmacology', 'carcinogenesis_and_mutagenesis_and_impairment_of_fertility', 'overdosage'])
dict_keys(['spl_product_data_elements', 'spl_unclassified_section', 'description', 'clinical_pharmacology', 'pharmacokinetics', 'indications_and_usage', 'contraindications', 'warnings', 'precautions', 'information_for_patients', 'drug_interactions', 'drug_and_or_laboratory_test_interactions', 'carcinogenesis_and_mutagenesis_and_impairment_of_fertility', 'pregnancy', 'teratogenic_effects', 'nursing_mothers', 'pediatric_use', 'adverse_reactions', 'overdosage', 'dosage_and_administration', 'how_supplied', 'storage_and_handling', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['spl_product_data_elements', 'active_ingredient', 'purpose', 'indications_and_usage', 'warnings', 'do_not_use', 'when_using', 'stop_use', 'keep_out_of_reach_of_children', 'dosage_and_administration', 'storage_and_handling', 'inactive_ingredient', 'questions', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['spl_product_data_elements', 'description', 'clinical_pharmacology', 'pharmacokinetics', 'indications_and_usage', 'contraindications', 'warnings', 'boxed_warning', 'precautions', 'information_for_patients', 'laboratory_tests', 'drug_interactions', 'drug_and_or_laboratory_test_interactions', 'carcinogenesis_and_mutagenesis_and_impairment_of_fertility', 'pregnancy', 'nursing_mothers', 'pediatric_use', 'adverse_reactions', 'overdosage', 'dosage_and_administration', 'dosage_and_administration_table', 'how_supplied', 'storage_and_handling', 'spl_unclassified_section', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['spl_product_data_elements', 'indications_and_usage', 'dosage_and_administration', 'dosage_and_administration_table', 'dosage_forms_and_strengths', 'contraindications', 'warnings_and_cautions', 'adverse_reactions', 'adverse_reactions_table', 'drug_interactions', 'use_in_specific_populations', 'use_in_specific_populations_table', 'pregnancy', 'pregnancy_table', 'labor_and_delivery', 'pediatric_use', 'geriatric_use', 'drug_abuse_and_dependence', 'controlled_substance', 'dependence', 'overdosage', 'description', 'clinical_pharmacology', 'mechanism_of_action', 'pharmacokinetics', 'nonclinical_toxicology', 'carcinogenesis_and_mutagenesis_and_impairment_of_fertility', 'clinical_studies', 'clinical_studies_table', 'how_supplied', 'information_for_patients', 'spl_medguide', 'spl_medguide_table', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['spl_product_data_elements', 'warnings_and_cautions', 'active_ingredient', 'purpose', 'indications_and_usage', 'warnings', 'do_not_use', 'when_using', 'ask_doctor', 'keep_out_of_reach_of_children', 'dosage_and_administration', 'storage_and_handling', 'inactive_ingredient', 'questions', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['effective_time', 'purpose', 'keep_out_of_reach_of_children', 'when_using', 'questions', 'pregnancy_or_breast_feeding', 'storage_and_handling', 'indications_and_usage', 'set_id', 'id', 'ask_doctor_or_pharmacist', 'active_ingredient', 'dosage_and_administration_table', 'inactive_ingredient', 'warnings', 'spl_product_data_elements', 'ask_doctor', 'openfda', 'version', 'dosage_and_administration', 'stop_use', 'do_not_use', 'package_label_principal_display_panel'])
dict_keys(['spl_product_data_elements', 'spl_unclassified_section', 'active_ingredient', 'active_ingredient_table', 'purpose', 'purpose_table', 'indications_and_usage', 'warnings', 'when_using', 'stop_use', 'pregnancy_or_breast_feeding', 'keep_out_of_reach_of_children', 'dosage_and_administration', 'storage_and_handling', 'inactive_ingredient', 'questions', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['spl_product_data_elements', 'active_ingredient', 'purpose', 'indications_and_usage', 'warnings', 'do_not_use', 'ask_doctor', 'ask_doctor_or_pharmacist', 'stop_use', 'pregnancy_or_breast_feeding', 'keep_out_of_reach_of_children', 'dosage_and_administration', 'storage_and_handling', 'inactive_ingredient', 'questions', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['effective_time', 'inactive_ingredient', 'purpose', 'keep_out_of_reach_of_children', 'when_using', 'spl_product_data_elements', 'openfda', 'version', 'dosage_and_administration', 'package_label_principal_display_panel', 'indications_and_usage', 'set_id', 'id', 'active_ingredient'])
dict_keys(['effective_time', 'inactive_ingredient', 'purpose', 'keep_out_of_reach_of_children', 'warnings', 'when_using', 'questions', 'spl_product_data_elements', 'openfda', 'version', 'dosage_and_administration', 'stop_use', 'storage_and_handling', 'do_not_use', 'package_label_principal_display_panel', 'indications_and_usage', 'set_id', 'id', 'active_ingredient'])
dict_keys(['effective_time', 'recent_major_changes', 'drug_interactions', 'geriatric_use', 'pharmacodynamics', 'description', 'nonclinical_toxicology', 'dosage_forms_and_strengths', 'clinical_pharmacology_table', 'storage_and_handling', 'mechanism_of_action', 'pharmacokinetics', 'clinical_studies_table', 'indications_and_usage', 'set_id', 'id', 'pediatric_use', 'contraindications', 'pregnancy', 'nursing_mothers', 'spl_product_data_elements', 'boxed_warning', 'warnings_and_cautions', 'adverse_reactions_table', 'openfda', 'recent_major_changes_table', 'version', 'dosage_and_administration', 'adverse_reactions', 'spl_unclassified_section', 'use_in_specific_populations', 'how_supplied', 'information_for_patients', 'clinical_studies', 'package_label_principal_display_panel', 'clinical_pharmacology', 'carcinogenesis_and_mutagenesis_and_impairment_of_fertility', 'overdosage'])
dict_keys(['spl_product_data_elements', 'active_ingredient', 'purpose', 'indications_and_usage', 'warnings', 'do_not_use', 'ask_doctor', 'ask_doctor_or_pharmacist', 'when_using', 'stop_use', 'pregnancy_or_breast_feeding', 'keep_out_of_reach_of_children', 'dosage_and_administration', 'storage_and_handling', 'inactive_ingredient', 'questions', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['spl_product_data_elements', 'spl_unclassified_section', 'active_ingredient', 'purpose', 'indications_and_usage', 'warnings', 'do_not_use', 'when_using', 'stop_use', 'keep_out_of_reach_of_children', 'dosage_and_administration', 'questions', 'storage_and_handling', 'inactive_ingredient', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['effective_time', 'drug_interactions', 'precautions', 'description', 'clinical_pharmacology_table', 'general_precautions', 'indications_and_usage', 'set_id', 'id', 'pediatric_use', 'contraindications', 'warnings', 'pregnancy', 'nursing_mothers', 'spl_product_data_elements', 'openfda', 'version', 'dosage_and_administration', 'adverse_reactions', 'spl_unclassified_section', 'laboratory_tests', 'how_supplied', 'package_label_principal_display_panel', 'clinical_pharmacology', 'carcinogenesis_and_mutagenesis_and_impairment_of_fertility', 'overdosage'])
dict_keys(['spl_product_data_elements', 'spl_unclassified_section', 'description', 'clinical_pharmacology', 'indications_and_usage', 'contraindications', 'warnings', 'precautions', 'general_precautions', 'information_for_patients', 'carcinogenesis_and_mutagenesis_and_impairment_of_fertility', 'pregnancy', 'teratogenic_effects', 'nonteratogenic_effects', 'nursing_mothers', 'pediatric_use', 'geriatric_use', 'adverse_reactions', 'dosage_and_administration', 'how_supplied', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['effective_time', 'contraindications', 'drug_abuse_and_dependence', 'precautions', 'warnings', 'spl_product_data_elements', 'description', 'openfda', 'version', 'dosage_and_administration', 'adverse_reactions', 'how_supplied_table', 'how_supplied', 'package_label_principal_display_panel', 'indications_and_usage', 'clinical_pharmacology', 'set_id', 'id', 'overdosage'])
dict_keys(['spl_product_data_elements', 'spl_unclassified_section', 'active_ingredient', 'purpose', 'indications_and_usage', 'warnings', 'when_using', 'stop_use', 'keep_out_of_reach_of_children', 'dosage_and_administration', 'inactive_ingredient', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['spl_product_data_elements', 'indications_and_usage', 'dosage_and_administration', 'active_ingredient', 'purpose', 'inactive_ingredient', 'questions', 'warnings', 'pregnancy_or_breast_feeding', 'keep_out_of_reach_of_children', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['effective_time', 'contraindications', 'precautions', 'warnings', 'spl_product_data_elements', 'description', 'adverse_reactions_table', 'openfda', 'version', 'dosage_and_administration', 'adverse_reactions', 'spl_unclassified_section', 'storage_and_handling', 'how_supplied', 'package_label_principal_display_panel', 'indications_and_usage', 'clinical_pharmacology', 'set_id', 'id', 'overdosage'])
dict_keys(['effective_time', 'keep_out_of_reach_of_children', 'warnings', 'spl_product_data_elements', 'openfda', 'version', 'dosage_and_administration', 'spl_unclassified_section', 'storage_and_handling', 'do_not_use', 'package_label_principal_display_panel', 'indications_and_usage', 'set_id', 'id', 'active_ingredient'])
dict_keys(['effective_time', 'references', 'precautions', 'description', 'clinical_pharmacology_table', 'indications_and_usage', 'set_id', 'id', 'dosage_and_administration_table', 'contraindications', 'warnings', 'spl_product_data_elements', 'boxed_warning', 'openfda', 'version', 'dosage_and_administration', 'adverse_reactions', 'animal_pharmacology_and_or_toxicology', 'spl_unclassified_section', 'how_supplied_table', 'how_supplied', 'references_table', 'package_label_principal_display_panel', 'clinical_pharmacology', 'overdosage'])
dict_keys(['effective_time', 'inactive_ingredient', 'purpose', 'keep_out_of_reach_of_children', 'warnings', 'when_using', 'spl_product_data_elements', 'openfda', 'version', 'dosage_and_administration', 'spl_unclassified_section', 'stop_use', 'package_label_principal_display_panel', 'indications_and_usage', 'set_id', 'id', 'active_ingredient'])
dict_keys(['spl_product_data_elements', 'indications_and_usage', 'dosage_and_administration', 'dosage_forms_and_strengths', 'contraindications', 'warnings_and_cautions', 'adverse_reactions', 'adverse_reactions_table', 'drug_interactions', 'use_in_specific_populations', 'pregnancy', 'pediatric_use', 'geriatric_use', 'overdosage', 'description', 'clinical_pharmacology', 'clinical_pharmacology_table', 'mechanism_of_action', 'pharmacodynamics', 'pharmacokinetics', 'pharmacokinetics_table', 'nonclinical_toxicology', 'carcinogenesis_and_mutagenesis_and_impairment_of_fertility', 'clinical_studies', 'clinical_studies_table', 'how_supplied', 'information_for_patients', 'spl_patient_package_insert', 'package_label_principal_display_panel', 'set_id', 'id', 'effective_time', 'version', 'openfda'])
dict_keys(['effective_time', 'inactive_ingredient', 'purpose', 'keep_out_of_reach_of_children', 'warnings', 'questions', 'spl_product_data_elements', 'openfda', 'version', 'dosage_and_administration', 'package_label_principal_display_panel', 'indications_and_usage', 'set_id', 'id', 'active_ingredient'])

In [5]:
python(len(drug_data))

NameError: name 'python' is not defined

In [6]:
drug_data=[]

In [7]:
for drug in data["results"]:
    record = {
        "brand_name": drug["openfda"]["brand_name"][0],
        "generic_name": drug["openfda"]["generic_name"][0],
        "manufacturer": drug["openfda"]["manufacturer_name"][0],
        "purpose": drug["purpose"][0]
    }

    drug_data.append(record)

KeyError: 'brand_name'

In [8]:
drug_data = []

for drug in data["results"]:
    if (
        "openfda" in drug
        and "brand_name" in drug["openfda"]
        and "generic_name" in drug["openfda"]
        and "manufacturer_name" in drug["openfda"]
        and "purpose" in drug
    ):
        record = {
            "brand_name": drug["openfda"]["brand_name"][0],
            "generic_name": drug["openfda"]["generic_name"][0],
            "manufacturer": drug["openfda"]["manufacturer_name"][0],
            "purpose": drug["purpose"][0]
        }

        drug_data.append(record)

In [9]:
print(len(drug_data))

11

In [10]:
drug_data = []

for drug in data["results"]:
    openfda = drug.get("openfda", {})

    record = {
        "brand_name": openfda.get("brand_name", ["N/A"])[0],
        "generic_name": openfda.get("generic_name", ["N/A"])[0],
        "manufacturer": openfda.get("manufacturer_name", ["N/A"])[0],
        "purpose": drug.get("purpose", ["N/A"])[0]
    }

    drug_data.append(record)

In [11]:
print(len(drug_data))

50

In [12]:
import pandas as pd

In [13]:
df = pd.DataFrame(drug_data)

In [14]:
print(df)

                                           brand_name  \
0                                             SILICEA
1                                                 N/A
2                                            Betadine
3                                                 N/A
4                                                 N/A
5                                            Naproxen
6                                                 N/A
7                          Moisturizing Antibacterial
8                                                 N/A
9                                                 N/A
10                                       Quick Action
11                                                N/A
12                                           Mekinist
13                                                N/A
14                                        Glimepiride
15                                                N/A
16                                      Methocarbamol
17                                          anti itch
18                                                N/A
19                                        Varenicline
20                                                N/A
21                                                N/A
22                                       Rescue Sleep
23                       Pain Reliever Extra Strength
24                                                N/A
25                                                N/A
26                                                N/A
27                                                N/A
28                          OASIS Tears Lubricant Eye
29                                                N/A
30                                                N/A
31                                                N/A
32     Thera Plus Maximum Strength Feminine Anti-Itch
33                                                N/A
34                                                N/A
35                                                N/A
36                                                N/A
37                                                N/A
38                           tamsulosin hydrochloride
39                                                N/A
40                                                N/A
41  Sure Complete Confidence Antiperspirant Deodor...
42                         Betamethasone Dipropionate
43                                                N/A
44                                                N/A
45                      Lights Povindone Iodine Scrub
46                                    Calcium Acetate
47                                                N/A
48                                                N/A
49                                                N/A

                                         generic_name  \
0                                             SILICEA
1                                                 N/A
2                                     POVIDONE-IODINE
3                                                 N/A
4                                                 N/A
5                                            NAPROXEN
6                                                 N/A
7                               BENZALKONIUM CHLORIDE
8                                                 N/A
9                                                 N/A
10                                     SALICYLIC ACID
11                                                N/A
12                                         TRAMETINIB
13                                                N/A
14                                        GLIMEPIRIDE
15                                                N/A
16                                      METHOCARBAMOL
17                                     HYDROCORTISONE
18                                                N/A
19                                        VARENICLINE
20                                                N/A
21                                                N/A
22  HELIANTHEMUM NUMMULARIUM FLOWER, CLEMATIS VITA...
23                                      ACETAMINOPHEN
24                                                N/A
25                                                N/A
26                                                N/A
27                                                N/A
28                                           GLYCERIN
29                                                N/A
30                                                N/A
31                                                N/A
32                             BENZOCAINE, RESORCINOL
33                                                N/A
34                                                N/A
35                                                N/A
36                                                N/A
37                                                N/A
38                           TAMSULOSIN HYDROCHLORIDE
39                                                N/A
40                                                N/A
41                             ALUMINUM CHLOROHYDRATE
42                         BETAMETHASONE DIPROPIONATE
43                                                N/A
44                                                N/A
45                                    POVIDONE-IODINE
46                                    CALCIUM ACETATE
47                                                N/A
48                                                N/A
49                                                N/A

                                   manufacturer  \
0   Rxhomeo Private Limited d.b.a. Rxhomeo, Inc
1                                           N/A
2            Atlantis Consumer Healthcare, Inc.
3                                           N/A
4                                           N/A
5                      A-S Medication Solutions
6                                           N/A
7                                  Walmart Inc.
8                                           N/A
9                                           N/A
10                                 Walmart Inc.
11                                          N/A
12         Novartis Pharmaceuticals Corporation
13                                          N/A
14                    American Health Packaging
15                                          N/A
16                             Proficient Rx LP
17                                 Meijer, Inc.
18                                          N/A
19                     Aurobindo Pharma Limited
20                                          N/A
21                                          N/A
22                        Nelson Bach USA, Ltd.
23                   Valu Merchandisers Company
24                                          N/A
25                                          N/A
26                                          N/A
27                                          N/A
28                          OASIS Medical, Inc.
29                                          N/A
30                                          N/A
31                                          N/A
32                     FOURSTAR GROUP USA, INC.
33                                          N/A
34                                          N/A
35                                          N/A
36                                          N/A
37                                          N/A
38                 XLCare Pharmaceuticals, Inc.
39                                          N/A
40                                          N/A
41                             Sodalis USA, LLC
42          Sun Pharmaceutical Industries, Inc.
43                                          N/A
44                                          N/A
45         Lights Medical Manufacture Co., Ltd.
46                              Cipla USA Inc.,
47                                          N/A
48                                          N/A
49                                          N/A

                                              purpose
0   USES USES: Temporary Relief - Acne, Boils* * C...
1                                   Purpose Sunscreen
2                        Purpose First aid Antiseptic
3            USES To relieve the symptoms of itching.
4                                                 N/A
5                                                 N/A
6                                  Purpose Antiseptic
7                               Purpose Antibacterial
8   Uses: For the management of acne helps clear u...
9                          Purpose-Nasal Decongestant
10                            Purpose Acne medication
11                    Use: Temporary relief of cough.
12                                                N/A
13                                                N/A
14                                                N/A
15                                                N/A
16                                                N/A
17                                  Purpose Anti-itch
18                                                N/A
19                                                N/A
20                     Purposes Antiseptic Antiseptic
21                Purpose Pain reliever/fever reducer
22  Active ingredients Each 5X (HPUS) Purpose Whit...
23                Purpose Pain reliever/fever reducer
24                                  PURPOSE Sunscreen
25                          Purpose Topical analgesic
26                                                N/A
27  Purposes Cough suppressant Expectorant Nasal d...
28                        Purpose lubricant Eye Drops
29                                                N/A
30                                                N/A
31                                                N/A
32                         Purpose External Analgesic
33  OTC - PURPOSE SECTION Cell Salt; Hemorrhoids; ...
34                                                N/A
35                                                N/A
36                                                N/A
37                              Purpose Antimicrobial
38                                                N/A
39                 Use: Temporary relief of headache.
40  Reduces occasional pain, pressure and inflamma...
41                             Purpose Antiperspirant
42                                                N/A
43                                 purpose Antiseptic
44                                                N/A
45                                Purpose: Antiseptic
46                                                N/A
47                         PURPOSE Purpose: Humectant
48     Uses: To help alleviate the symptoms of grief.
49  PURPOSE dry scaly skin dry and cracked skin, b...

In [15]:
print(df.shape)

(50, 4)

In [16]:
df.head

<bound method NDFrame.head of                                            brand_name  \
0                                             SILICEA
1                                                 N/A
2                                            Betadine
3                                                 N/A
4                                                 N/A
5                                            Naproxen
6                                                 N/A
7                          Moisturizing Antibacterial
8                                                 N/A
9                                                 N/A
10                                       Quick Action
11                                                N/A
12                                           Mekinist
13                                                N/A
14                                        Glimepiride
15                                                N/A
16                                      Methocarbamol
17                                          anti itch
18                                                N/A
19                                        Varenicline
20                                                N/A
21                                                N/A
22                                       Rescue Sleep
23                       Pain Reliever Extra Strength
24                                                N/A
25                                                N/A
26                                                N/A
27                                                N/A
28                          OASIS Tears Lubricant Eye
29                                                N/A
30                                                N/A
31                                                N/A
32     Thera Plus Maximum Strength Feminine Anti-Itch
33                                                N/A
34                                                N/A
35                                                N/A
36                                                N/A
37                                                N/A
38                           tamsulosin hydrochloride
39                                                N/A
40                                                N/A
41  Sure Complete Confidence Antiperspirant Deodor...
42                         Betamethasone Dipropionate
43                                                N/A
44                                                N/A
45                      Lights Povindone Iodine Scrub
46                                    Calcium Acetate
47                                                N/A
48                                                N/A
49                                                N/A

                                         generic_name  \
0                                             SILICEA
1                                                 N/A
2                                     POVIDONE-IODINE
3                                                 N/A
4                                                 N/A
5                                            NAPROXEN
6                                                 N/A
7                               BENZALKONIUM CHLORIDE
8                                                 N/A
9                                                 N/A
10                                     SALICYLIC ACID
11                                                N/A
12                                         TRAMETINIB
13                                                N/A
14                                        GLIMEPIRIDE
15                                                N/A
16                                      METHOCARBAMOL
17                                     HYDROCORTISONE
18                                                N/A
19                                        VARENICLINE
20                                                N/A
21                                                N/A
22  HELIANTHEMUM NUMMULARIUM FLOWER, CLEMATIS VITA...
23                                      ACETAMINOPHEN
24                                                N/A
25                                                N/A
26                                                N/A
27                                                N/A
28                                           GLYCERIN
29                                                N/A
30                                                N/A
31                                                N/A
32                             BENZOCAINE, RESORCINOL
33                                                N/A
34                                                N/A
35                                                N/A
36                                                N/A
37                                                N/A
38                           TAMSULOSIN HYDROCHLORIDE
39                                                N/A
40                                                N/A
41                             ALUMINUM CHLOROHYDRATE
42                         BETAMETHASONE DIPROPIONATE
43                                                N/A
44                                                N/A
45                                    POVIDONE-IODINE
46                                    CALCIUM ACETATE
47                                                N/A
48                                                N/A
49                                                N/A

                                   manufacturer  \
0   Rxhomeo Private Limited d.b.a. Rxhomeo, Inc
1                                           N/A
2            Atlantis Consumer Healthcare, Inc.
3                                           N/A
4                                           N/A
5                      A-S Medication Solutions
6                                           N/A
7                                  Walmart Inc.
8                                           N/A
9                                           N/A
10                                 Walmart Inc.
11                                          N/A
12         Novartis Pharmaceuticals Corporation
13                                          N/A
14                    American Health Packaging
15                                          N/A
16                             Proficient Rx LP
17                                 Meijer, Inc.
18                                          N/A
19                     Aurobindo Pharma Limited
20                                          N/A
21                                          N/A
22                        Nelson Bach USA, Ltd.
23                   Valu Merchandisers Company
24                                          N/A
25                                          N/A
26                                          N/A
27                                          N/A
28                          OASIS Medical, Inc.
29                                          N/A
30                                          N/A
31                                          N/A
32                     FOURSTAR GROUP USA, INC.
33                                          N/A
34                                          N/A
35                                          N/A
36                                          N/A
37                                          N/A
38                 XLCare Pharmaceuticals, Inc.
39                                          N/A
40                                          N/A
41                             Sodalis USA, LLC
42          Sun Pharmaceutical Industries, Inc.
43                                          N/A
44                                          N/A
45         Lights Medical Manufacture Co., Ltd.
46                              Cipla USA Inc.,
47                                          N/A
48                                          N/A
49                                          N/A

                                              purpose
0   USES USES: Temporary Relief - Acne, Boils* * C...
1                                   Purpose Sunscreen
2                        Purpose First aid Antiseptic
3            USES To relieve the symptoms of itching.
4                                                 N/A
5                                                 N/A
6                                  Purpose Antiseptic
7                               Purpose Antibacterial
8   Uses: For the management of acne helps clear u...
9                          Purpose-Nasal Decongestant
10                            Purpose Acne medication
11                    Use: Temporary relief of cough.
12                                                N/A
13                                                N/A
14                                                N/A
15                                                N/A
16                                                N/A
17                                  Purpose Anti-itch
18                                                N/A
19                                                N/A
20                     Purposes Antiseptic Antiseptic
21                Purpose Pain reliever/fever reducer
22  Active ingredients Each 5X (HPUS) Purpose Whit...
23                Purpose Pain reliever/fever reducer
24                                  PURPOSE Sunscreen
25                          Purpose Topical analgesic
26                                                N/A
27  Purposes Cough suppressant Expectorant Nasal d...
28                        Purpose lubricant Eye Drops
29                                                N/A
30                                                N/A
31                                                N/A
32                         Purpose External Analgesic
33  OTC - PURPOSE SECTION Cell Salt; Hemorrhoids; ...
34                                                N/A
35                                                N/A
36                                                N/A
37                              Purpose Antimicrobial
38                                                N/A
39                 Use: Temporary relief of headache.
40  Reduces occasional pain, pressure and inflamma...
41                             Purpose Antiperspirant
42                                                N/A
43                                 purpose Antiseptic
44                                                N/A
45                                Purpose: Antiseptic
46                                                N/A
47                         PURPOSE Purpose: Humectant
48     Uses: To help alleviate the symptoms of grief.
49  PURPOSE dry scaly skin dry and cracked skin, b...  >

In [17]:
df.head()
df.info

<bound method DataFrame.info of                                            brand_name  \
0                                             SILICEA
1                                                 N/A
2                                            Betadine
3                                                 N/A
4                                                 N/A
5                                            Naproxen
6                                                 N/A
7                          Moisturizing Antibacterial
8                                                 N/A
9                                                 N/A
10                                       Quick Action
11                                                N/A
12                                           Mekinist
13                                                N/A
14                                        Glimepiride
15                                                N/A
16                                      Methocarbamol
17                                          anti itch
18                                                N/A
19                                        Varenicline
20                                                N/A
21                                                N/A
22                                       Rescue Sleep
23                       Pain Reliever Extra Strength
24                                                N/A
25                                                N/A
26                                                N/A
27                                                N/A
28                          OASIS Tears Lubricant Eye
29                                                N/A
30                                                N/A
31                                                N/A
32     Thera Plus Maximum Strength Feminine Anti-Itch
33                                                N/A
34                                                N/A
35                                                N/A
36                                                N/A
37                                                N/A
38                           tamsulosin hydrochloride
39                                                N/A
40                                                N/A
41  Sure Complete Confidence Antiperspirant Deodor...
42                         Betamethasone Dipropionate
43                                                N/A
44                                                N/A
45                      Lights Povindone Iodine Scrub
46                                    Calcium Acetate
47                                                N/A
48                                                N/A
49                                                N/A

                                         generic_name  \
0                                             SILICEA
1                                                 N/A
2                                     POVIDONE-IODINE
3                                                 N/A
4                                                 N/A
5                                            NAPROXEN
6                                                 N/A
7                               BENZALKONIUM CHLORIDE
8                                                 N/A
9                                                 N/A
10                                     SALICYLIC ACID
11                                                N/A
12                                         TRAMETINIB
13                                                N/A
14                                        GLIMEPIRIDE
15                                                N/A
16                                      METHOCARBAMOL
17                                     HYDROCORTISONE
18                                                N/A
19                                        VARENICLINE
20                                                N/A
21                                                N/A
22  HELIANTHEMUM NUMMULARIUM FLOWER, CLEMATIS VITA...
23                                      ACETAMINOPHEN
24                                                N/A
25                                                N/A
26                                                N/A
27                                                N/A
28                                           GLYCERIN
29                                                N/A
30                                                N/A
31                                                N/A
32                             BENZOCAINE, RESORCINOL
33                                                N/A
34                                                N/A
35                                                N/A
36                                                N/A
37                                                N/A
38                           TAMSULOSIN HYDROCHLORIDE
39                                                N/A
40                                                N/A
41                             ALUMINUM CHLOROHYDRATE
42                         BETAMETHASONE DIPROPIONATE
43                                                N/A
44                                                N/A
45                                    POVIDONE-IODINE
46                                    CALCIUM ACETATE
47                                                N/A
48                                                N/A
49                                                N/A

                                   manufacturer  \
0   Rxhomeo Private Limited d.b.a. Rxhomeo, Inc
1                                           N/A
2            Atlantis Consumer Healthcare, Inc.
3                                           N/A
4                                           N/A
5                      A-S Medication Solutions
6                                           N/A
7                                  Walmart Inc.
8                                           N/A
9                                           N/A
10                                 Walmart Inc.
11                                          N/A
12         Novartis Pharmaceuticals Corporation
13                                          N/A
14                    American Health Packaging
15                                          N/A
16                             Proficient Rx LP
17                                 Meijer, Inc.
18                                          N/A
19                     Aurobindo Pharma Limited
20                                          N/A
21                                          N/A
22                        Nelson Bach USA, Ltd.
23                   Valu Merchandisers Company
24                                          N/A
25                                          N/A
26                                          N/A
27                                          N/A
28                          OASIS Medical, Inc.
29                                          N/A
30                                          N/A
31                                          N/A
32                     FOURSTAR GROUP USA, INC.
33                                          N/A
34                                          N/A
35                                          N/A
36                                          N/A
37                                          N/A
38                 XLCare Pharmaceuticals, Inc.
39                                          N/A
40                                          N/A
41                             Sodalis USA, LLC
42          Sun Pharmaceutical Industries, Inc.
43                                          N/A
44                                          N/A
45         Lights Medical Manufacture Co., Ltd.
46                              Cipla USA Inc.,
47                                          N/A
48                                          N/A
49                                          N/A

                                              purpose
0   USES USES: Temporary Relief - Acne, Boils* * C...
1                                   Purpose Sunscreen
2                        Purpose First aid Antiseptic
3            USES To relieve the symptoms of itching.
4                                                 N/A
5                                                 N/A
6                                  Purpose Antiseptic
7                               Purpose Antibacterial
8   Uses: For the management of acne helps clear u...
9                          Purpose-Nasal Decongestant
10                            Purpose Acne medication
11                    Use: Temporary relief of cough.
12                                                N/A
13                                                N/A
14                                                N/A
15                                                N/A
16                                                N/A
17                                  Purpose Anti-itch
18                                                N/A
19                                                N/A
20                     Purposes Antiseptic Antiseptic
21                Purpose Pain reliever/fever reducer
22  Active ingredients Each 5X (HPUS) Purpose Whit...
23                Purpose Pain reliever/fever reducer
24                                  PURPOSE Sunscreen
25                          Purpose Topical analgesic
26                                                N/A
27  Purposes Cough suppressant Expectorant Nasal d...
28                        Purpose lubricant Eye Drops
29                                                N/A
30                                                N/A
31                                                N/A
32                         Purpose External Analgesic
33  OTC - PURPOSE SECTION Cell Salt; Hemorrhoids; ...
34                                                N/A
35                                                N/A
36                                                N/A
37                              Purpose Antimicrobial
38                                                N/A
39                 Use: Temporary relief of headache.
40  Reduces occasional pain, pressure and inflamma...
41                             Purpose Antiperspirant
42                                                N/A
43                                 purpose Antiseptic
44                                                N/A
45                                Purpose: Antiseptic
46                                                N/A
47                         PURPOSE Purpose: Humectant
48     Uses: To help alleviate the symptoms of grief.
49  PURPOSE dry scaly skin dry and cracked skin, b...  >

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand_name    50 non-null     str
 1   generic_name  50 non-null     str
 2   manufacturer  50 non-null     str
 3   purpose       50 non-null     str
dtypes: str(4)
memory usage: 5.2 KB

In [1]:
df.isnull().sum()

NameError: name 'df' is not defined

In [1]:
import requests
import pandas as pd

In [2]:
url = "https://api.fda.gov/drug/label.json?limit=50"

response = requests.get(url)
data = response.json()

In [3]:
drug_data = []

for drug in data["results"]:
    openfda = drug.get("openfda", {})

    record = {
        "brand_name": openfda.get("brand_name", ["N/A"])[0],
        "generic_name": openfda.get("generic_name", ["N/A"])[0],
        "manufacturer": openfda.get("manufacturer_name", ["N/A"])[0],
        "purpose": drug.get("purpose", ["N/A"])[0]
    }

    drug_data.append(record)

In [4]:
df = pd.DataFrame(drug_data)

In [5]:
df.shape

(50, 4)

In [6]:
df.isnull().sum()

brand_name      0
generic_name    0
manufacturer    0
purpose         0
dtype: int64

In [7]:
(df == "N/A").sum()

brand_name      31
generic_name    31
manufacturer    31
purpose         20
dtype: int64

In [8]:
df.duplicated().sum()df.duplicated().sum()

SyntaxError: invalid syntax (3161963168.py, line 1)

In [9]:
df.duplicated().sum()

np.int64(11)

In [10]:
df[df.duplicated()]

   brand_name generic_name manufacturer purpose
13        N/A          N/A          N/A     N/A
15        N/A          N/A          N/A     N/A
18        N/A          N/A          N/A     N/A
26        N/A          N/A          N/A     N/A
29        N/A          N/A          N/A     N/A
30        N/A          N/A          N/A     N/A
31        N/A          N/A          N/A     N/A
34        N/A          N/A          N/A     N/A
35        N/A          N/A          N/A     N/A
36        N/A          N/A          N/A     N/A
44        N/A          N/A          N/A     N/A

In [11]:
df = df.drop_duplicates()

In [12]:
df.shape

(39, 4)

In [13]:
for col in df.columns:
    print(f"\n{col}:")
    print(df[col].unique())

brand_name:
<ArrowStringArray>
[                                                             'SILICEA',
                                                                  'N/A',
                                                             'Betadine',
                                                             'Naproxen',
                                           'Moisturizing Antibacterial',
                                                         'Quick Action',
                                                             'Mekinist',
                                                          'Glimepiride',
                                                        'Methocarbamol',
                                                            'anti itch',
                                                          'Varenicline',
                                                         'Rescue Sleep',
                                         'Pain Reliever Extra Strength',
                                            'OASIS Tears Lubricant Eye',
                       'Thera Plus Maximum Strength Feminine Anti-Itch',
                                             'tamsulosin hydrochloride',
 'Sure Complete Confidence Antiperspirant Deodorant Aerosol, Unscented',
                                           'Betamethasone Dipropionate',
                                        'Lights Povindone Iodine Scrub',
                                                      'Calcium Acetate']
Length: 20, dtype: str

generic_name:
<ArrowStringArray>
[                                                                                                                                                                      'SILICEA',
                                                                                                                                                                           'N/A',
                                                                                                                                                               'POVIDONE-IODINE',
                                                                                                                                                                      'NAPROXEN',
                                                                                                                                                         'BENZALKONIUM CHLORIDE',
                                                                                                                                                                'SALICYLIC ACID',
                                                                                                                                                                    'TRAMETINIB',
                                                                                                                                                                   'GLIMEPIRIDE',
                                                                                                                                                                 'METHOCARBAMOL',
                                                                                                                                                                'HYDROCORTISONE',
                                                                                                                                                                   'VARENICLINE',
 'HELIANTHEMUM NUMMULARIUM FLOWER, CLEMATIS VITALBA FLOWER, IMPATIENS GLANDULIFERA FLOWER, PRUNUS CERASIFERA FLOWER, ORNITHOGALUM UMBELLATUM, AND AESCULUS HIPPOCASTANUM FLOWER',
                                                                                                                                                                 'ACETAMINOPHEN',
                                                                                                                                                                      'GLYCERIN',
                                                                                                                                                        'BENZOCAINE, RESORCINOL',
                                                                                                                                                      'TAMSULOSIN HYDROCHLORIDE',
                                                                                                                                                        'ALUMINUM CHLOROHYDRATE',
                                                                                                                                                    'BETAMETHASONE DIPROPIONATE',
                                                                                                                                                               'CALCIUM ACETATE']
Length: 19, dtype: str

manufacturer:
<ArrowStringArray>
['Rxhomeo Private Limited d.b.a. Rxhomeo, Inc',
                                         'N/A',
          'Atlantis Consumer Healthcare, Inc.',
                    'A-S Medication Solutions',
                                'Walmart Inc.',
        'Novartis Pharmaceuticals Corporation',
                   'American Health Packaging',
                            'Proficient Rx LP',
                                'Meijer, Inc.',
                    'Aurobindo Pharma Limited',
                       'Nelson Bach USA, Ltd.',
                  'Valu Merchandisers Company',
                         'OASIS Medical, Inc.',
                    'FOURSTAR GROUP USA, INC.',
                'XLCare Pharmaceuticals, Inc.',
                            'Sodalis USA, LLC',
         'Sun Pharmaceutical Industries, Inc.',
        'Lights Medical Manufacture Co., Ltd.',
                             'Cipla USA Inc.,']
Length: 19, dtype: str

purpose:
<ArrowStringArray>
[                                                                                                                                                                                                                                                                                                'USES USES: Temporary Relief - Acne, Boils* * Claims based on traditional homeopathic practice, not accepted medical evidence. Not FDA evaluated.',
                                                                                                                                                                                                                                                                                                                                                                                                                                'Purpose Sunscreen',
                                                                                                                                                                                                                                                                                                                                                                                                                     'Purpose First aid Antiseptic',
                                                                                                                                                                                                                                                                                                                                                                                                         'USES To relieve the symptoms of itching.',
                                                                                                                                                                                                                                                                                                                                                                                                                                              'N/A',
                                                                                                                                                                                                                                                                                                                                                                                                                               'Purpose Antiseptic',
                                                                                                                                                                                                                                                                                                                                                                                                                            'Purpose Antibacterial',
        'Uses: For the management of acne helps clear up acne blemishes, black heads, helps prevent the development of new acne pimples penetrates pores to reduce the number of acne pimples, white heads and black heads help keep skin clear of new acne pimples, white heads and black heads helps prevent new acne pimples, white heads and black heads from forming help prevent the development of new pimples, white heads and black heads',
                                                                                                                                                                                                                                                                                                                                                                                                                       'Purpose-Nasal Decongestant',
                                                                                                                                                                                                                                                                                                                                                                                                                          'Purpose Acne medication',
                                                                                                                                                                                                                                                                                                                                                                                                                  'Use: Temporary relief of cough.',
                                                                                                                                                                                                                                                                                                                                                                                                                                'Purpose Anti-itch',
                                                                                                                                                                                                                                                                                                                                                                                                                   'Purposes Antiseptic Antiseptic',
                                                                                                                                                                                                                                                                                                                                                                                                              'Purpose Pain reliever/fever reducer',
 'Active ingredients Each 5X (HPUS) Purpose White Chestnut (Aesculus hippocastanum) Relief from repetitive thoughts Rock Rose (Helianthemum nummularium) Courage and presence of mind Clematis (Clematis vitalba) Focus when ungrounded Impatiens (Impatiens glandulifera) Patience with problems and people Cherry Plum (Prunus cerasifera) Balanced mind when losing control Star of Bethlehem (Ornithogalum umbellatum) Softens impact of shock',
                                                                                                                                                                                                                                                                                                                                                                                                                                'PURPOSE Sunscreen',
                                                                                                                                                                                                                                                                                                                                                                                                                        'Purpose Topical analgesic',
                                                                                                                                                                                                                                                                                                                                                                                        'Purposes Cough suppressant Expectorant Nasal decongestant',
                                                                                                                                                                                                                                                                                                                                                                                                                      'Purpose lubricant Eye Drops',
                                                                                                                                                                                                                                                                                                                                                                                                                       'Purpose External Analgesic',
                                                                                                                                                                                                                                                                                                                             'OTC - PURPOSE SECTION Cell Salt; Hemorrhoids; Keloids; Migraine; Nervousness; Constipation before and during menses.',
                                                                                                                                                                                                                                                                                                                                                                                                                            'Purpose Antimicrobial',
                                                                                                                                                                                                                                                                                                                                                                                                               'Use: Temporary relief of headache.',
                                                                                                                                                                                                                                                                                                                                                                                 'Reduces occasional pain, pressure and inflammation from sciatica',
                                                                                                                                                                                                                                                                                                                                                                                                                           'Purpose Antiperspirant',
                                                                                                                                                                                                                                                                                                                                                                                                                               'purpose Antiseptic',
                                                                                                                                                                                                                                                                                                                                                                                                                              'Purpose: Antiseptic',
                                                                                                                                                                                                                                                                                                                                                                                                                       'PURPOSE Purpose: Humectant',
                                                                                                                                                                                                                                                                                                                                                                                                   'Uses: To help alleviate the symptoms of grief.',
                                                                                                                                                                                                                                                              'PURPOSE dry scaly skin dry and cracked skin, body rash itching and redness intense itching behind the ears, redness, dry and cracked skin itching dry skin and itching itching rash']
Length: 30, dtype: str

In [14]:
(df == "N/A").sum()

brand_name      20
generic_name    20
manufacturer    20
purpose          9
dtype: int64

In [15]:
df = df.replace("N/A", pd.NA)

In [16]:
df.isnull().sum()

brand_name      20
generic_name    20
manufacturer    20
purpose          9
dtype: int64

In [17]:
df.dropna().shape

(11, 4)

In [18]:
df.dropna()

,brand_name,generic_name,manufacturer,purpose
0,SILICEA,SILICEA,"Rxhomeo Private Limited d.b.a. Rxhomeo, Inc","USES USES: Temporary Relief - Acne, Boils* * C..."
2,Betadine,POVIDONE-IODINE,"Atlantis Consumer Healthcare, Inc.",Purpose First aid Antiseptic
7,Moisturizing Antibacterial,BENZALKONIUM CHLORIDE,Walmart Inc.,Purpose Antibacterial
10,Quick Action,SALICYLIC ACID,Walmart Inc.,Purpose Acne medication
17,anti itch,HYDROCORTISONE,"Meijer, Inc.",Purpose Anti-itch
22,Rescue Sleep,"HELIANTHEMUM NUMMULARIUM FLOWER, CLEMATIS VITA...","Nelson Bach USA, Ltd.",Active ingredients Each 5X (HPUS) Purpose Whit...
23,Pain Reliever Extra Strength,ACETAMINOPHEN,Valu Merchandisers Company,Purpose Pain reliever/fever reducer
28,OASIS Tears Lubricant Eye,GLYCERIN,"OASIS Medical, Inc.",Purpose lubricant Eye Drops
32,Thera Plus Maximum Strength Feminine Anti-Itch,"BENZOCAINE, RESORCINOL","FOURSTAR GROUP USA, INC.",Purpose External Analgesic
41,Sure Complete Confidence Antiperspirant Deodor...,ALUMINUM CHLOROHYDRATE,"Sodalis USA, LLC",Purpose Antiperspirant
45,Lights Povindone Iodine Scrub,POVIDONE-IODINE,"Lights Medical Manufacture Co., Ltd.",Purpose: Antiseptic

In [19]:
df.isnull().sum(axis=1)

0     0
1     3
2     0
3     3
4     4
5     1
6     3
7     0
8     3
9     3
10    0
11    3
12    1
14    1
16    1
17    0
19    1
20    3
21    3
22    0
23    0
24    3
25    3
27    3
28    0
32    0
33    3
37    3
38    1
39    3
40    3
41    0
42    1
43    3
45    0
46    1
47    3
48    3
49    3
dtype: int64

In [20]:
df.isnull().sum()

brand_name      20
generic_name    20
manufacturer    20
purpose          9
dtype: int64

In [21]:
(df.isnull().mean() * 100).round(2)

brand_name      51.28
generic_name    51.28
manufacturer    51.28
purpose         23.08
dtype: float64

In [22]:
df[df.isnull().any(axis=1)]

,brand_name,generic_name,manufacturer,purpose
1,NaN,NaN,NaN,Purpose Sunscreen
3,NaN,NaN,NaN,USES To relieve the symptoms of itching.
4,NaN,NaN,NaN,NaN
5,Naproxen,NAPROXEN,A-S Medication Solutions,NaN
6,NaN,NaN,NaN,Purpose Antiseptic
8,NaN,NaN,NaN,Uses: For the management of acne helps clear u...
9,NaN,NaN,NaN,Purpose-Nasal Decongestant
11,NaN,NaN,NaN,Use: Temporary relief of cough.
12,Mekinist,TRAMETINIB,Novartis Pharmaceuticals Corporation,NaN
14,Glimepiride,GLIMEPIRIDE,American Health Packaging,NaN
16,Methocarbamol,METHOCARBAMOL,Proficient Rx LP,NaN
19,Varenicline,VARENICLINE,Aurobindo Pharma Limited,NaN
20,NaN,NaN,NaN,Purposes Antiseptic Antiseptic
21,NaN,NaN,NaN,Purpose Pain reliever/fever reducer
24,NaN,NaN,NaN,PURPOSE Sunscreen
25,NaN,NaN,NaN,Purpose Topical analgesic
27,NaN,NaN,NaN,Purposes Cough suppressant Expectorant Nasal d...
33,NaN,NaN,NaN,OTC - PURPOSE SECTION Cell Salt; Hemorrhoids; ...
37,NaN,NaN,NaN,Purpose Antimicrobial
38,tamsulosin hydrochloride,TAMSULOSIN HYDROCHLORIDE,"XLCare Pharmaceuticals, Inc.",NaN
39,NaN,NaN,NaN,Use: Temporary relief of headache.
40,NaN,NaN,NaN,"Reduces occasional pain, pressure and inflamma..."
42,Betamethasone Dipropionate,BETAMETHASONE DIPROPIONATE,"Sun Pharmaceutical Industries, Inc.",NaN
43,NaN,NaN,NaN,purpose Antiseptic
46,Calcium Acetate,CALCIUM ACETATE,"Cipla USA Inc.,",NaN
47,NaN,NaN,NaN,PURPOSE Purpose: Humectant
48,NaN,NaN,NaN,Uses: To help alleviate the symptoms of grief.
49,NaN,NaN,NaN,"PURPOSE dry scaly skin dry and cracked skin, b..."

In [23]:
df[df.isnull().all(axis=1)]

  brand_name generic_name manufacturer purpose
4        NaN          NaN          NaN     NaN

In [24]:
df = df.dropna(how="all")

In [25]:
df.shape

(38, 4)

In [26]:
df.info()

<class 'pandas.DataFrame'>
Index: 38 entries, 0 to 49
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand_name    19 non-null     str
 1   generic_name  19 non-null     str
 2   manufacturer  19 non-null     str
 3   purpose       30 non-null     str
dtypes: str(4)
memory usage: 4.7 KB

In [27]:
df.isnull().sum()

brand_name      19
generic_name    19
manufacturer    19
purpose          8
dtype: int64

In [28]:
df.isnull().sum()

brand_name      19
generic_name    19
manufacturer    19
purpose          8
dtype: int64

In [29]:
df[df["brand_name"].isna()]

,brand_name,generic_name,manufacturer,purpose
1,NaN,NaN,NaN,Purpose Sunscreen
3,NaN,NaN,NaN,USES To relieve the symptoms of itching.
6,NaN,NaN,NaN,Purpose Antiseptic
8,NaN,NaN,NaN,Uses: For the management of acne helps clear u...
9,NaN,NaN,NaN,Purpose-Nasal Decongestant
11,NaN,NaN,NaN,Use: Temporary relief of cough.
20,NaN,NaN,NaN,Purposes Antiseptic Antiseptic
21,NaN,NaN,NaN,Purpose Pain reliever/fever reducer
24,NaN,NaN,NaN,PURPOSE Sunscreen
25,NaN,NaN,NaN,Purpose Topical analgesic
27,NaN,NaN,NaN,Purposes Cough suppressant Expectorant Nasal d...
33,NaN,NaN,NaN,OTC - PURPOSE SECTION Cell Salt; Hemorrhoids; ...
37,NaN,NaN,NaN,Purpose Antimicrobial
39,NaN,NaN,NaN,Use: Temporary relief of headache.
40,NaN,NaN,NaN,"Reduces occasional pain, pressure and inflamma..."
43,NaN,NaN,NaN,purpose Antiseptic
47,NaN,NaN,NaN,PURPOSE Purpose: Humectant
48,NaN,NaN,NaN,Uses: To help alleviate the symptoms of grief.
49,NaN,NaN,NaN,"PURPOSE dry scaly skin dry and cracked skin, b..."

In [30]:
df[df["brand_name"].isna()][["generic_name", "manufacturer", "purpose"]]

,generic_name,manufacturer,purpose
1,NaN,NaN,Purpose Sunscreen
3,NaN,NaN,USES To relieve the symptoms of itching.
6,NaN,NaN,Purpose Antiseptic
8,NaN,NaN,Uses: For the management of acne helps clear u...
9,NaN,NaN,Purpose-Nasal Decongestant
11,NaN,NaN,Use: Temporary relief of cough.
20,NaN,NaN,Purposes Antiseptic Antiseptic
21,NaN,NaN,Purpose Pain reliever/fever reducer
24,NaN,NaN,PURPOSE Sunscreen
25,NaN,NaN,Purpose Topical analgesic
27,NaN,NaN,Purposes Cough suppressant Expectorant Nasal d...
33,NaN,NaN,OTC - PURPOSE SECTION Cell Salt; Hemorrhoids; ...
37,NaN,NaN,Purpose Antimicrobial
39,NaN,NaN,Use: Temporary relief of headache.
40,NaN,NaN,"Reduces occasional pain, pressure and inflamma..."
43,NaN,NaN,purpose Antiseptic
47,NaN,NaN,PURPOSE Purpose: Humectant
48,NaN,NaN,Uses: To help alleviate the symptoms of grief.
49,NaN,NaN,"PURPOSE dry scaly skin dry and cracked skin, b..."

In [31]:
df[df["purpose"].isna()]

,brand_name,generic_name,manufacturer,purpose
5,Naproxen,NAPROXEN,A-S Medication Solutions,NaN
12,Mekinist,TRAMETINIB,Novartis Pharmaceuticals Corporation,NaN
14,Glimepiride,GLIMEPIRIDE,American Health Packaging,NaN
16,Methocarbamol,METHOCARBAMOL,Proficient Rx LP,NaN
19,Varenicline,VARENICLINE,Aurobindo Pharma Limited,NaN
38,tamsulosin hydrochloride,TAMSULOSIN HYDROCHLORIDE,"XLCare Pharmaceuticals, Inc.",NaN
42,Betamethasone Dipropionate,BETAMETHASONE DIPROPIONATE,"Sun Pharmaceutical Industries, Inc.",NaN
46,Calcium Acetate,CALCIUM ACETATE,"Cipla USA Inc.,",NaN

In [32]:
df.isnull().sum()

brand_name      19
generic_name    19
manufacturer    19
purpose          8
dtype: int64

In [33]:
df.shape

(38, 4)

In [34]:
df["purpose"] = df["purpose"].str.replace(
    r"(?i)^(purpose|uses?|purposes?)\s*[-:]?\s*",
    "",
    regex=True
)

In [35]:
df["purpose"].dropna().head(10)

0     USES: Temporary Relief - Acne, Boils* * Claims...
1                                             Sunscreen
2                                  First aid Antiseptic
3                   To relieve the symptoms of itching.
6                                            Antiseptic
7                                         Antibacterial
8     For the management of acne helps clear up acne...
9                                    Nasal Decongestant
10                                      Acne medication
11                           Temporary relief of cough.
Name: purpose, dtype: str

In [36]:
df["purpose"] = df["purpose"].str.replace(
    r"(?i)^(purpose|uses?|purposes?)\s*[:\-]?\s*",
    "",
    regex=True
)

In [37]:
df["purpose"].dropna().head(12)

0     Temporary Relief - Acne, Boils* * Claims based...
1                                             Sunscreen
2                                  First aid Antiseptic
3                   To relieve the symptoms of itching.
6                                            Antiseptic
7                                         Antibacterial
8     For the management of acne helps clear up acne...
9                                    Nasal Decongestant
10                                      Acne medication
11                           Temporary relief of cough.
17                                            Anti-itch
20                              s Antiseptic Antiseptic
Name: purpose, dtype: str

In [38]:
for col in ["brand_name", "generic_name", "manufacturer"]:
    df[col] = df[col].str.strip()

In [39]:
df.head

<bound method NDFrame.head of                                            brand_name  \
0                                             SILICEA
1                                                 NaN
2                                            Betadine
3                                                 NaN
5                                            Naproxen
6                                                 NaN
7                          Moisturizing Antibacterial
8                                                 NaN
9                                                 NaN
10                                       Quick Action
11                                                NaN
12                                           Mekinist
14                                        Glimepiride
16                                      Methocarbamol
17                                          anti itch
19                                        Varenicline
20                                                NaN
21                                                NaN
22                                       Rescue Sleep
23                       Pain Reliever Extra Strength
24                                                NaN
25                                                NaN
27                                                NaN
28                          OASIS Tears Lubricant Eye
32     Thera Plus Maximum Strength Feminine Anti-Itch
33                                                NaN
37                                                NaN
38                           tamsulosin hydrochloride
39                                                NaN
40                                                NaN
41  Sure Complete Confidence Antiperspirant Deodor...
42                         Betamethasone Dipropionate
43                                                NaN
45                      Lights Povindone Iodine Scrub
46                                    Calcium Acetate
47                                                NaN
48                                                NaN
49                                                NaN

                                         generic_name  \
0                                             SILICEA
1                                                 NaN
2                                     POVIDONE-IODINE
3                                                 NaN
5                                            NAPROXEN
6                                                 NaN
7                               BENZALKONIUM CHLORIDE
8                                                 NaN
9                                                 NaN
10                                     SALICYLIC ACID
11                                                NaN
12                                         TRAMETINIB
14                                        GLIMEPIRIDE
16                                      METHOCARBAMOL
17                                     HYDROCORTISONE
19                                        VARENICLINE
20                                                NaN
21                                                NaN
22  HELIANTHEMUM NUMMULARIUM FLOWER, CLEMATIS VITA...
23                                      ACETAMINOPHEN
24                                                NaN
25                                                NaN
27                                                NaN
28                                           GLYCERIN
32                             BENZOCAINE, RESORCINOL
33                                                NaN
37                                                NaN
38                           TAMSULOSIN HYDROCHLORIDE
39                                                NaN
40                                                NaN
41                             ALUMINUM CHLOROHYDRATE
42                         BETAMETHASONE DIPROPIONATE
43                                                NaN
45                                    POVIDONE-IODINE
46                                    CALCIUM ACETATE
47                                                NaN
48                                                NaN
49                                                NaN

                                   manufacturer  \
0   Rxhomeo Private Limited d.b.a. Rxhomeo, Inc
1                                           NaN
2            Atlantis Consumer Healthcare, Inc.
3                                           NaN
5                      A-S Medication Solutions
6                                           NaN
7                                  Walmart Inc.
8                                           NaN
9                                           NaN
10                                 Walmart Inc.
11                                          NaN
12         Novartis Pharmaceuticals Corporation
14                    American Health Packaging
16                             Proficient Rx LP
17                                 Meijer, Inc.
19                     Aurobindo Pharma Limited
20                                          NaN
21                                          NaN
22                        Nelson Bach USA, Ltd.
23                   Valu Merchandisers Company
24                                          NaN
25                                          NaN
27                                          NaN
28                          OASIS Medical, Inc.
32                     FOURSTAR GROUP USA, INC.
33                                          NaN
37                                          NaN
38                 XLCare Pharmaceuticals, Inc.
39                                          NaN
40                                          NaN
41                             Sodalis USA, LLC
42          Sun Pharmaceutical Industries, Inc.
43                                          NaN
45         Lights Medical Manufacture Co., Ltd.
46                              Cipla USA Inc.,
47                                          NaN
48                                          NaN
49                                          NaN

                                              purpose
0   Temporary Relief - Acne, Boils* * Claims based...
1                                           Sunscreen
2                                First aid Antiseptic
3                 To relieve the symptoms of itching.
5                                                 NaN
6                                          Antiseptic
7                                       Antibacterial
8   For the management of acne helps clear up acne...
9                                  Nasal Decongestant
10                                    Acne medication
11                         Temporary relief of cough.
12                                                NaN
14                                                NaN
16                                                NaN
17                                          Anti-itch
19                                                NaN
20                            s Antiseptic Antiseptic
21                        Pain reliever/fever reducer
22  Active ingredients Each 5X (HPUS) Purpose Whit...
23                        Pain reliever/fever reducer
24                                          Sunscreen
25                                  Topical analgesic
27  s Cough suppressant Expectorant Nasal deconges...
28                                lubricant Eye Drops
32                                 External Analgesic
33  OTC - PURPOSE SECTION Cell Salt; Hemorrhoids; ...
37                                      Antimicrobial
38                                                NaN
39                      Temporary relief of headache.
40  Reduces occasional pain, pressure and inflamma...
41                                     Antiperspirant
42                                                NaN
43                                         Antiseptic
45                                         Antiseptic
46                                                NaN
47                                          Humectant
48           To help alleviate the symptoms of grief.
49  dry scaly skin dry and cracked skin, body rash...  >

In [40]:
df.head()

,brand_name,generic_name,manufacturer,purpose
0,SILICEA,SILICEA,"Rxhomeo Private Limited d.b.a. Rxhomeo, Inc","Temporary Relief - Acne, Boils* * Claims based..."
1,NaN,NaN,NaN,Sunscreen
2,Betadine,POVIDONE-IODINE,"Atlantis Consumer Healthcare, Inc.",First aid Antiseptic
3,NaN,NaN,NaN,To relieve the symptoms of itching.
5,Naproxen,NAPROXEN,A-S Medication Solutions,NaN

In [41]:
for col in df.columns:
    df[col] = df[col].str.strip()

In [42]:
df.head()

,brand_name,generic_name,manufacturer,purpose
0,SILICEA,SILICEA,"Rxhomeo Private Limited d.b.a. Rxhomeo, Inc","Temporary Relief - Acne, Boils* * Claims based..."
1,NaN,NaN,NaN,Sunscreen
2,Betadine,POVIDONE-IODINE,"Atlantis Consumer Healthcare, Inc.",First aid Antiseptic
3,NaN,NaN,NaN,To relieve the symptoms of itching.
5,Naproxen,NAPROXEN,A-S Medication Solutions,NaN

In [43]:
df["brand_name"].dropna().unique()

<ArrowStringArray>
[                                                             'SILICEA',
                                                             'Betadine',
                                                             'Naproxen',
                                           'Moisturizing Antibacterial',
                                                         'Quick Action',
                                                             'Mekinist',
                                                          'Glimepiride',
                                                        'Methocarbamol',
                                                            'anti itch',
                                                          'Varenicline',
                                                         'Rescue Sleep',
                                         'Pain Reliever Extra Strength',
                                            'OASIS Tears Lubricant Eye',
                       'Thera Plus Maximum Strength Feminine Anti-Itch',
                                             'tamsulosin hydrochloride',
 'Sure Complete Confidence Antiperspirant Deodorant Aerosol, Unscented',
                                           'Betamethasone Dipropionate',
                                        'Lights Povindone Iodine Scrub',
                                                      'Calcium Acetate']
Length: 19, dtype: str

In [44]:
df["generic_name"].dropna().unique()

<ArrowStringArray>
[                                                                                                                                                                      'SILICEA',
                                                                                                                                                               'POVIDONE-IODINE',
                                                                                                                                                                      'NAPROXEN',
                                                                                                                                                         'BENZALKONIUM CHLORIDE',
                                                                                                                                                                'SALICYLIC ACID',
                                                                                                                                                                    'TRAMETINIB',
                                                                                                                                                                   'GLIMEPIRIDE',
                                                                                                                                                                 'METHOCARBAMOL',
                                                                                                                                                                'HYDROCORTISONE',
                                                                                                                                                                   'VARENICLINE',
 'HELIANTHEMUM NUMMULARIUM FLOWER, CLEMATIS VITALBA FLOWER, IMPATIENS GLANDULIFERA FLOWER, PRUNUS CERASIFERA FLOWER, ORNITHOGALUM UMBELLATUM, AND AESCULUS HIPPOCASTANUM FLOWER',
                                                                                                                                                                 'ACETAMINOPHEN',
                                                                                                                                                                      'GLYCERIN',
                                                                                                                                                        'BENZOCAINE, RESORCINOL',
                                                                                                                                                      'TAMSULOSIN HYDROCHLORIDE',
                                                                                                                                                        'ALUMINUM CHLOROHYDRATE',
                                                                                                                                                    'BETAMETHASONE DIPROPIONATE',
                                                                                                                                                               'CALCIUM ACETATE']
Length: 18, dtype: str

In [45]:
df["manufacturer"].dropna().unique()

<ArrowStringArray>
['Rxhomeo Private Limited d.b.a. Rxhomeo, Inc',
          'Atlantis Consumer Healthcare, Inc.',
                    'A-S Medication Solutions',
                                'Walmart Inc.',
        'Novartis Pharmaceuticals Corporation',
                   'American Health Packaging',
                            'Proficient Rx LP',
                                'Meijer, Inc.',
                    'Aurobindo Pharma Limited',
                       'Nelson Bach USA, Ltd.',
                  'Valu Merchandisers Company',
                         'OASIS Medical, Inc.',
                    'FOURSTAR GROUP USA, INC.',
                'XLCare Pharmaceuticals, Inc.',
                            'Sodalis USA, LLC',
         'Sun Pharmaceutical Industries, Inc.',
        'Lights Medical Manufacture Co., Ltd.',
                             'Cipla USA Inc.,']
Length: 18, dtype: str

In [46]:
df["brand_name"].dropna().unique()

<ArrowStringArray>
[                                                             'SILICEA',
                                                             'Betadine',
                                                             'Naproxen',
                                           'Moisturizing Antibacterial',
                                                         'Quick Action',
                                                             'Mekinist',
                                                          'Glimepiride',
                                                        'Methocarbamol',
                                                            'anti itch',
                                                          'Varenicline',
                                                         'Rescue Sleep',
                                         'Pain Reliever Extra Strength',
                                            'OASIS Tears Lubricant Eye',
                       'Thera Plus Maximum Strength Feminine Anti-Itch',
                                             'tamsulosin hydrochloride',
 'Sure Complete Confidence Antiperspirant Deodorant Aerosol, Unscented',
                                           'Betamethasone Dipropionate',
                                        'Lights Povindone Iodine Scrub',
                                                      'Calcium Acetate']
Length: 19, dtype: str

In [47]:
df["brand_name"] = df["brand_name"].replace({
    "anti itch": "Anti Itch",
    "tamsulosin hydrochloride": "Tamsulosin Hydrochloride"
})

In [48]:
df["brand_name"] = df["brand_name"].replace({
    "anti itch": "Anti Itch",
    "tamsulosin hydrochloride": "Tamsulosin Hydrochloride"
})

In [49]:
df["brand_name"].dropna().unique()

<ArrowStringArray>
[                                                             'SILICEA',
                                                             'Betadine',
                                                             'Naproxen',
                                           'Moisturizing Antibacterial',
                                                         'Quick Action',
                                                             'Mekinist',
                                                          'Glimepiride',
                                                        'Methocarbamol',
                                                            'Anti Itch',
                                                          'Varenicline',
                                                         'Rescue Sleep',
                                         'Pain Reliever Extra Strength',
                                            'OASIS Tears Lubricant Eye',
                       'Thera Plus Maximum Strength Feminine Anti-Itch',
                                             'Tamsulosin Hydrochloride',
 'Sure Complete Confidence Antiperspirant Deodorant Aerosol, Unscented',
                                           'Betamethasone Dipropionate',
                                        'Lights Povindone Iodine Scrub',
                                                      'Calcium Acetate']
Length: 19, dtype: str

In [50]:
df["purpose"].dropna().unique()

<ArrowStringArray>
[                                                                                                                                                                                                                                                                                                           'Temporary Relief - Acne, Boils* * Claims based on traditional homeopathic practice, not accepted medical evidence. Not FDA evaluated.',
                                                                                                                                                                                                                                                                                                                                                                                                                                        'Sunscreen',
                                                                                                                                                                                                                                                                                                                                                                                                                             'First aid Antiseptic',
                                                                                                                                                                                                                                                                                                                                                                                                              'To relieve the symptoms of itching.',
                                                                                                                                                                                                                                                                                                                                                                                                                                       'Antiseptic',
                                                                                                                                                                                                                                                                                                                                                                                                                                    'Antibacterial',
              'For the management of acne helps clear up acne blemishes, black heads, helps prevent the development of new acne pimples penetrates pores to reduce the number of acne pimples, white heads and black heads help keep skin clear of new acne pimples, white heads and black heads helps prevent new acne pimples, white heads and black heads from forming help prevent the development of new pimples, white heads and black heads',
                                                                                                                                                                                                                                                                                                                                                                                                                               'Nasal Decongestant',
                                                                                                                                                                                                                                                                                                                                                                                                                                  'Acne medication',
                                                                                                                                                                                                                                                                                                                                                                                                                       'Temporary relief of cough.',
                                                                                                                                                                                                                                                                                                                                                                                                                                        'Anti-itch',
                                                                                                                                                                                                                                                                                                                                                                                                                          's Antiseptic Antiseptic',
                                                                                                                                                                                                                                                                                                                                                                                                                      'Pain reliever/fever reducer',
 'Active ingredients Each 5X (HPUS) Purpose White Chestnut (Aesculus hippocastanum) Relief from repetitive thoughts Rock Rose (Helianthemum nummularium) Courage and presence of mind Clematis (Clematis vitalba) Focus when ungrounded Impatiens (Impatiens glandulifera) Patience with problems and people Cherry Plum (Prunus cerasifera) Balanced mind when losing control Star of Bethlehem (Ornithogalum umbellatum) Softens impact of shock',
                                                                                                                                                                                                                                                                                                                                                                                                                                'Topical analgesic',
                                                                                                                                                                                                                                                                                                                                                                                               's Cough suppressant Expectorant Nasal decongestant',
                                                                                                                                                                                                                                                                                                                                                                                                                              'lubricant Eye Drops',
                                                                                                                                                                                                                                                                                                                                                                                                                               'External Analgesic',
                                                                                                                                                                                                                                                                                                                             'OTC - PURPOSE SECTION Cell Salt; Hemorrhoids; Keloids; Migraine; Nervousness; Constipation before and during menses.',
                                                                                                                                                                                                                                                                                                                                                                                                                                    'Antimicrobial',
                                                                                                                                                                                                                                                                                                                                                                                                                    'Temporary relief of headache.',
                                                                                                                                                                                                                                                                                                                                                                                 'Reduces occasional pain, pressure and inflammation from sciatica',
                                                                                                                                                                                                                                                                                                                                                                                                                                   'Antiperspirant',
                                                                                                                                                                                                                                                                                                                                                                                                                                        'Humectant',
                                                                                                                                                                                                                                                                                                                                                                                                         'To help alleviate the symptoms of grief.',
                                                                                                                                                                                                                                                                      'dry scaly skin dry and cracked skin, body rash itching and redness intense itching behind the ears, redness, dry and cracked skin itching dry skin and itching itching rash']
Length: 26, dtype: str

In [51]:
df[df["purpose"].str.startswith(("s ", "OTC", "Active ingredients"), na=False)][["purpose"]]

                                              purpose
20                            s Antiseptic Antiseptic
22  Active ingredients Each 5X (HPUS) Purpose Whit...
27  s Cough suppressant Expectorant Nasal deconges...
33  OTC - PURPOSE SECTION Cell Salt; Hemorrhoids; ...

In [52]:
df.loc[20, "purpose"] = "Antiseptic"
df.loc[27, "purpose"] = "Cough suppressant; Expectorant; Nasal decongestant"

In [53]:
df.loc[[20, 22, 27, 33], "purpose"]

20                                           Antiseptic
22    Active ingredients Each 5X (HPUS) Purpose Whit...
27    Cough suppressant; Expectorant; Nasal deconges...
33    OTC - PURPOSE SECTION Cell Salt; Hemorrhoids; ...
Name: purpose, dtype: str

In [54]:
df.loc[22, "purpose"] = df.loc[22, "purpose"].replace(
    "Active ingredients Each 5X (HPUS) Purpose ",
    ""
)

In [55]:
df.loc[22, "purpose"]

'White Chestnut (Aesculus hippocastanum) Relief from repetitive thoughts Rock Rose (Helianthemum nummularium) Courage and presence of mind Clematis (Clematis vitalba) Focus when ungrounded Impatiens (Impatiens glandulifera) Patience with problems and people Cherry Plum (Prunus cerasifera) Balanced mind when losing control Star of Bethlehem (Ornithogalum umbellatum) Softens impact of shock'

In [56]:
df.loc[33, "purpose"] = df.loc[33, "purpose"].replace(
    "OTC - PURPOSE SECTION ",
    ""
)

In [57]:
df.loc[33, "purpose"]

'Cell Salt; Hemorrhoids; Keloids; Migraine; Nervousness; Constipation before and during menses.'

In [58]:
df.shape

(38, 4)

In [59]:
df.isnull().sum()

brand_name      19
generic_name    19
manufacturer    19
purpose          8
dtype: int64

In [60]:
df.head()

,brand_name,generic_name,manufacturer,purpose
0,SILICEA,SILICEA,"Rxhomeo Private Limited d.b.a. Rxhomeo, Inc","Temporary Relief - Acne, Boils* * Claims based..."
1,NaN,NaN,NaN,Sunscreen
2,Betadine,POVIDONE-IODINE,"Atlantis Consumer Healthcare, Inc.",First aid Antiseptic
3,NaN,NaN,NaN,To relieve the symptoms of itching.
5,Naproxen,NAPROXEN,A-S Medication Solutions,NaN

In [61]:
df.to_csv("cleaned_drug_data.csv", index=False)

In [62]:
import os
os.path.exists("cleaned_drug_data.csv")

True